//! Unit tests for `crate::model_metadata::live`.

use super::*;

const FIXTURE: &str = include_str!("../../../tests/fixtures/models-dev/api-subset.json");

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("fixture JSON")
}

/// The Rust extraction reproduces the maintainer refresh script's outputs for
/// the same catalog. The expected files are generated by
/// `scripts/refresh-models-dev-pricing.py --source` (see
/// `scripts/test_refresh_models_dev_metadata.py`).
#[test]
fn extraction_matches_the_refresh_script_byte_for_byte_in_meaning() {
    let (extracted, rejected) = extract(&fixture()).unwrap();
    assert!(rejected.is_empty(), "{rejected:?}");
    let names: BTreeMap<String, String> = serde_json::from_str(include_str!(
        "../../../tests/fixtures/models-dev/expected-names.json"
    ))
    .unwrap();
    let pricing: BTreeMap<String, LivePricing> = serde_json::from_str(include_str!(
        "../../../tests/fixtures/models-dev/expected-pricing.json"
    ))
    .unwrap();
    let capabilities: BTreeMap<String, Value> = serde_json::from_str(include_str!(
        "../../../tests/fixtures/models-dev/expected-capabilities.json"
    ))
    .unwrap();
    assert_eq!(extracted.names, names);
    assert_eq!(extracted.pricing, pricing);
    assert_eq!(extracted.capabilities, capabilities);
}

#[test]
fn prices_convert_to_microdollars_rounding_half_up_like_decimal() {
    let convert = |value: Value| microdollars(Some(&value));
    assert_eq!(convert(serde_json::json!(0.15)), Ok(150_000));
    assert_eq!(convert(serde_json::json!(2)), Ok(2_000_000));
    assert_eq!(convert(serde_json::json!(1.5625)), Ok(1_562_500));
    assert_eq!(convert(serde_json::json!(12.5)), Ok(12_500_000));
    assert_eq!(convert(serde_json::json!(0.0000005)), Ok(1));
    assert_eq!(convert(serde_json::json!(0.0000004)), Ok(0));
    assert_eq!(convert(serde_json::json!(1e-7)), Ok(0));
    assert_eq!(convert(serde_json::json!(0)), Ok(0));
    assert_eq!(microdollars(None), Ok(0));
    assert_eq!(microdollars(Some(&Value::Null)), Ok(0));
    for invalid in [
        serde_json::json!(-1),
        serde_json::json!("0.5"),
        serde_json::json!(true),
        serde_json::json!(1e20),
    ] {
        assert!(convert(invalid.clone()).is_err(), "{invalid}");
    }
}

fn catalog_with(openai_models: Value) -> Value {
    serde_json::json!({ "openai": { "models": openai_models } })
}

/// `openai/gpt-5` is in the compiled snapshot at $1.25 / $10 per million.
#[test]
fn live_prices_are_checked_against_the_snapshot_per_model() {
    assert!(super::super::lookup_pricing_rates("openai/gpt-5").is_some());
    let tool = |input: f64, output: f64| {
        serde_json::json!({"name": "Model", "tool_call": true,
                           "cost": {"input": input, "output": output}})
    };
    let (metadata, rejected) = live_metadata_from_models_dev(&catalog_with(serde_json::json!({
        "gpt-5": tool(0.1, 10.0),
        "gpt-5-mini": tool(0.25, 0.0),
        "gpt-9-new": tool(0.0, 1.0),
        "gpt-9-priced": tool(1.0, 8.0),
    })))
    .unwrap();
    // A >10x drop and a new zero rate keep the built-in data or stay unpriced.
    assert!(!metadata.pricing.contains_key("openai/gpt-5"));
    assert!(!metadata.pricing.contains_key("openai/gpt-9-new"));
    assert_eq!(
        metadata.pricing["openai/gpt-9-priced"],
        LivePricing {
            input: 1_000_000,
            output: 8_000_000,
            cache_read: 0,
            cache_write_5m: 0,
            reasoning: None,
        }
    );
    assert!(rejected
        .iter()
        .any(|line| line == "openai/gpt-5: input price dropped more than 10x"));
    assert!(rejected
        .iter()
        .any(|line| line.starts_with("openai/gpt-9-new: a new model needs non-zero")));
    if super::super::lookup_pricing_rates("openai/gpt-5-mini").is_some_and(|rates| rates.output > 0)
    {
        assert!(!metadata.pricing.contains_key("openai/gpt-5-mini"));
    }
}

#[test]
fn malformed_prices_and_limits_leave_out_only_their_model() {
    let (metadata, rejected) = live_metadata_from_models_dev(&catalog_with(serde_json::json!({
        "bad-price": {"name": "Bad", "cost": {"input": "cheap", "output": 1}},
        "bad-limit": {"name": "Wide", "limit": {"context": 1e12, "output": 4096}},
        "fine": {"name": "Fine", "limit": {"context": 0, "output": 8192},
                 "cost": {"input": 1, "output": 2}},
    })))
    .unwrap();
    assert!(!metadata.pricing.contains_key("openai/bad-price"));
    assert!(!metadata.capabilities.contains_key("openai/bad-limit"));
    // Zero and output-above-context limits exist upstream and stay accepted.
    assert!(metadata.capabilities.contains_key("openai/fine"));
    assert!(metadata.pricing.contains_key("openai/fine"));
    assert_eq!(metadata.names["openai/bad-price"], "Bad");
    assert_eq!(rejected.len(), 2, "{rejected:?}");
}

#[test]
fn a_catalog_without_usable_records_is_an_error() {
    assert!(live_metadata_from_models_dev(&serde_json::json!([])).is_err());
    assert!(live_metadata_from_models_dev(&serde_json::json!({})).is_err());
}

/// Lookups prefer a live record and fall back per record to the snapshot.
#[test]
fn overlay_lookups_prefer_live_records_and_fall_back_per_record() {
    let (metadata, _) = live_metadata_from_models_dev(&fixture()).unwrap();
    let overlay: &'static super::super::LiveOverlay =
        Box::leak(Box::new(super::super::LiveOverlay::new(metadata)));
    // Live-only models resolve by exact key and by their unique leaf.
    assert_eq!(
        super::super::lookup_key_in(Some(overlay), "openai/gpt-9-preview"),
        Some("GPT-9 Preview")
    );
    assert_eq!(
        super::super::lookup_key_in(Some(overlay), "gpt-9-preview"),
        Some("GPT-9 Preview")
    );
    assert_eq!(
        super::super::lookup_key_in(None, "openai/gpt-9-preview"),
        None
    );
    // Records the live catalog lacks keep the compiled snapshot's answer.
    assert_eq!(
        super::super::lookup_key_in(Some(overlay), "alibaba/qwen3.6-27b"),
        Some("Qwen3.6 27B")
    );
    let live = super::super::lookup_pricing_in(Some(overlay), "openai/gpt-9-preview").unwrap();
    assert_eq!(live.input, crate::pricing::TokenRate(1_250_000));
    assert_eq!(live.reasoning, Some(crate::pricing::TokenRate(12_500_000)));
    assert_eq!(
        super::super::lookup_pricing_in(Some(overlay), "openai/gpt-5"),
        super::super::lookup_pricing_in(None, "openai/gpt-5")
    );
    let record =
        super::super::capability_metadata_in(Some(overlay), "baseten/zai-org/GLM-5.2").unwrap();
    assert_eq!(record["modalities"]["input"], serde_json::json!(["text"]));
}

#[test]
fn every_billed_bucket_is_checked_against_the_snapshot() {
    let snapshot = LivePricing {
        input: 1_000_000,
        output: 2_000_000,
        cache_read: 100_000,
        cache_write_5m: 1_250_000,
        reasoning: Some(5_000_000),
    };
    assert!(check_pricing(&snapshot, Some(snapshot)).is_ok());
    for bucket in ["cache_read", "cache_write", "reasoning"] {
        for rate in [0, 1] {
            let mut live = snapshot;
            match bucket {
                "cache_read" => live.cache_read = rate,
                "cache_write" => live.cache_write_5m = rate,
                _ => live.reasoning = Some(rate),
            }
            let rejection = check_pricing(&live, Some(snapshot)).unwrap_err();
            assert!(rejection.starts_with(bucket), "{rejection}");
        }
    }
    let expensive_reasoning = LivePricing {
        reasoning: Some(50_000_000),
        ..snapshot
    };
    assert!(check_pricing(
        &LivePricing {
            reasoning: None,
            ..snapshot
        },
        Some(expensive_reasoning)
    )
    .unwrap_err()
    .starts_with("reasoning"));
    // An unpublished built-in cache price may acquire a valid live rate.
    let unpublished = LivePricing {
        cache_read: 0,
        cache_write_5m: 0,
        ..snapshot
    };
    assert!(check_pricing(&snapshot, Some(unpublished)).is_ok());
    // A known free cache bucket remains legitimately free.
    assert!(check_pricing(&unpublished, Some(unpublished)).is_ok());
}
