import { Type } from '@sinclair/typebox';
import { unsupported } from '../lib/errors.mjs';
export { Type };
export const StringEnum = (values, options = {}) => Type.Unsafe({ ...options, type: 'string', enum: values });
export const getModel = () => unsupported('pi-ai.getModel', 'model selection and inventory remain host-owned');
export const getModels = () => unsupported('pi-ai.getModels', 'model inventory was not supplied by octet');
export const complete = () => unsupported('pi-ai.complete', 'Rust owns inference; no Pi provider runtime is loaded');
export const stream = () => unsupported('pi-ai.stream', 'Rust owns inference');
export const completeSimple = complete;
export const streamSimple = stream;
