import Foundation

private func runtimeText(_ value: String, path: String, limit: Int = OctetProtocolLimits.publicTextBytes) throws -> String {
    try OctetJSONBounds.validateText(value, path: path, limit: limit, multiline: false)
    guard !value.isEmpty else { throw OctetDecodeError.invalidPublicText(path: path) }
    return value
}

public struct ChildAgentStatus: Codable, Equatable, Sendable {
    public let id: RuntimeId; public let parentId: RuntimeId?; public let objective: String; public let state: ChildAgentState; public let queuedAtMs: UInt64; public let startedAtMs: UInt64?; public let updatedAtMs: UInt64; public let finishedAtMs: UInt64?; public let outcome: String?
    private enum CodingKeys: String, CodingKey { case id, parentId, objective, state, queuedAtMs, startedAtMs, updatedAtMs, finishedAtMs, outcome }
    public init(id: RuntimeId, parentId: RuntimeId? = nil, objective: String, state: ChildAgentState, queuedAtMs: UInt64, startedAtMs: UInt64? = nil, updatedAtMs: UInt64, finishedAtMs: UInt64? = nil, outcome: String? = nil) { self.id=id;self.parentId=parentId;self.objective=objective;self.state=state;self.queuedAtMs=queuedAtMs;self.startedAtMs=startedAtMs;self.updatedAtMs=updatedAtMs;self.finishedAtMs=finishedAtMs;self.outcome=outcome }
    public init(from decoder: Decoder) throws { let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["id","parentId","objective","state","queuedAtMs","startedAtMs","updatedAtMs","finishedAtMs","outcome"],path:"childAgent");id=try c.decode(RuntimeId.self,forKey:.id);parentId=try c.decodeIfPresent(RuntimeId.self,forKey:.parentId);objective=try runtimeText(c.decode(String.self,forKey:.objective),path:"childAgent.objective",limit:4*1024);state=try c.decode(ChildAgentState.self,forKey:.state);queuedAtMs=try c.decode(UInt64.self,forKey:.queuedAtMs);startedAtMs=try c.decodeIfPresent(UInt64.self,forKey:.startedAtMs);updatedAtMs=try c.decode(UInt64.self,forKey:.updatedAtMs);finishedAtMs=try c.decodeIfPresent(UInt64.self,forKey:.finishedAtMs);outcome=try c.decodeIfPresent(String.self,forKey:.outcome);if let outcome { _=try runtimeText(outcome,path:"childAgent.outcome",limit:2*1024) } }
}

public struct McpServerStatus: Codable, Equatable, Sendable {
    public let id: RuntimeId; public let label: String; public let state: McpServerState; public let restartCount: UInt32; public let configuredAtMs: UInt64; public let updatedAtMs: UInt64; public let failure: String?
    private enum CodingKeys: String, CodingKey { case id,label,state,restartCount,configuredAtMs,updatedAtMs,failure }
    public init(id:RuntimeId,label:String,state:McpServerState,restartCount:UInt32,configuredAtMs:UInt64,updatedAtMs:UInt64,failure:String?=nil){self.id=id;self.label=label;self.state=state;self.restartCount=restartCount;self.configuredAtMs=configuredAtMs;self.updatedAtMs=updatedAtMs;self.failure=failure}
    public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["id","label","state","restartCount","configuredAtMs","updatedAtMs","failure"],path:"mcpServer");id=try c.decode(RuntimeId.self,forKey:.id);label=try runtimeText(c.decode(String.self,forKey:.label),path:"mcpServer.label",limit:192);state=try c.decode(McpServerState.self,forKey:.state);restartCount=try c.decode(UInt32.self,forKey:.restartCount);configuredAtMs=try c.decode(UInt64.self,forKey:.configuredAtMs);updatedAtMs=try c.decode(UInt64.self,forKey:.updatedAtMs);failure=try c.decodeIfPresent(String.self,forKey:.failure);if let failure{_=try runtimeText(failure,path:"mcpServer.failure",limit:2048)}}
}

public struct CatalogContribution: Codable, Equatable, Comparable, Sendable {
    public let kind: ContributionKind; public let id: RuntimeId; public let label: String
    private enum CodingKeys:String,CodingKey{case kind,id,label}
    public init(kind:ContributionKind,id:RuntimeId,label:String){self.kind=kind;self.id=id;self.label=label}
    public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["kind","id","label"],path:"catalogContribution");kind=try c.decode(ContributionKind.self,forKey:.kind);id=try c.decode(RuntimeId.self,forKey:.id);label=try runtimeText(c.decode(String.self,forKey:.label),path:"catalogContribution.label",limit:192)}
    public static func < (lhs: Self, rhs: Self) -> Bool { (lhs.kind.rawValue,lhs.id.value,lhs.label) < (rhs.kind.rawValue,rhs.id.value,rhs.label) }
}

public struct TrustedCatalogEntry: Codable, Equatable, Sendable {
    public let id: RuntimeId; public let label: String; public let kind: TrustedCatalogKind; public let enabled: Bool; public let contributions: [CatalogContribution]
    private enum CodingKeys:String,CodingKey{case id,label,kind,enabled,contributions}
    public init(id:RuntimeId,label:String,kind:TrustedCatalogKind,enabled:Bool,contributions:[CatalogContribution]){self.id=id;self.label=label;self.kind=kind;self.enabled=enabled;self.contributions=contributions}
    public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["id","label","kind","enabled","contributions"],path:"catalogEntry");id=try c.decode(RuntimeId.self,forKey:.id);label=try runtimeText(c.decode(String.self,forKey:.label),path:"catalogEntry.label",limit:192);kind=try c.decode(TrustedCatalogKind.self,forKey:.kind);enabled=try c.decode(Bool.self,forKey:.enabled);contributions=try c.decode([CatalogContribution].self,forKey:.contributions);guard contributions.count<=64 else{throw OctetDecodeError.invalidValue(path:"catalogEntry.contributions",message:"too many contributions")}}
}

public enum CatalogReloadStatus: Codable, Equatable, Sendable {
    case idle
    case running(reloadId:RuntimeId,retainedGeneration:UInt64,startedAtMs:UInt64)
    case succeeded(reloadId:RuntimeId,generation:UInt64,startedAtMs:UInt64,finishedAtMs:UInt64)
    case failed(reloadId:RuntimeId,retainedGeneration:UInt64,startedAtMs:UInt64,finishedAtMs:UInt64,failure:String)
    private enum CodingKeys:String,CodingKey{case state,reloadId,retainedGeneration,startedAtMs,generation,finishedAtMs,failure}
    public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["state","reloadId","retainedGeneration","startedAtMs","generation","finishedAtMs","failure"],path:"catalogReload");switch try c.decode(String.self,forKey:.state){case "idle":self = .idle;case "running":self = .running(reloadId:try c.decode(RuntimeId.self,forKey:.reloadId),retainedGeneration:try c.decode(UInt64.self,forKey:.retainedGeneration),startedAtMs:try c.decode(UInt64.self,forKey:.startedAtMs));case "succeeded":self = .succeeded(reloadId:try c.decode(RuntimeId.self,forKey:.reloadId),generation:try c.decode(UInt64.self,forKey:.generation),startedAtMs:try c.decode(UInt64.self,forKey:.startedAtMs),finishedAtMs:try c.decode(UInt64.self,forKey:.finishedAtMs));case "failed":let f=try c.decode(String.self,forKey:.failure);self = .failed(reloadId:try c.decode(RuntimeId.self,forKey:.reloadId),retainedGeneration:try c.decode(UInt64.self,forKey:.retainedGeneration),startedAtMs:try c.decode(UInt64.self,forKey:.startedAtMs),finishedAtMs:try c.decode(UInt64.self,forKey:.finishedAtMs),failure:try runtimeText(f,path:"catalogReload.failure",limit:2048));default:throw OctetDecodeError.invalidValue(path:"catalogReload.state",message:"unknown state")}}
    public func encode(to encoder:Encoder)throws{var c=encoder.container(keyedBy:CodingKeys.self);switch self{case .idle:try c.encode("idle",forKey:.state);case let .running(id,retained,started):try c.encode("running",forKey:.state);try c.encode(id,forKey:.reloadId);try c.encode(retained,forKey:.retainedGeneration);try c.encode(started,forKey:.startedAtMs);case let .succeeded(id,generation,started,finished):try c.encode("succeeded",forKey:.state);try c.encode(id,forKey:.reloadId);try c.encode(generation,forKey:.generation);try c.encode(started,forKey:.startedAtMs);try c.encode(finished,forKey:.finishedAtMs);case let .failed(id,retained,started,finished,failure):try c.encode("failed",forKey:.state);try c.encode(id,forKey:.reloadId);try c.encode(retained,forKey:.retainedGeneration);try c.encode(started,forKey:.startedAtMs);try c.encode(finished,forKey:.finishedAtMs);try c.encode(failure,forKey:.failure)}}
}

public struct TrustedCatalogStatus: Codable, Equatable, Sendable {
    public let generation: UInt64; public let updatedAtMs: UInt64; public let reload: CatalogReloadStatus; public let entries: [TrustedCatalogEntry]
    private enum CodingKeys:String,CodingKey{case generation,updatedAtMs,reload,entries}
    public init(generation:UInt64,updatedAtMs:UInt64,reload:CatalogReloadStatus,entries:[TrustedCatalogEntry]){self.generation=generation;self.updatedAtMs=updatedAtMs;self.reload=reload;self.entries=entries}
    public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["generation","updatedAtMs","reload","entries"],path:"catalog");generation=try c.decode(UInt64.self,forKey:.generation);updatedAtMs=try c.decode(UInt64.self,forKey:.updatedAtMs);reload=try c.decode(CatalogReloadStatus.self,forKey:.reload);entries=try c.decode([TrustedCatalogEntry].self,forKey:.entries);guard entries.count<=256 else{throw OctetDecodeError.invalidValue(path:"catalog.entries",message:"too many entries")}}
}

public struct DiagnosticCounts: Codable, Equatable, Sendable {
    public let errors: UInt32; public let warnings: UInt32; public let information: UInt32; public let hints: UInt32
    private enum CodingKeys:String,CodingKey{case errors,warnings,information,hints}
    public init(errors:UInt32,warnings:UInt32,information:UInt32,hints:UInt32){self.errors=errors;self.warnings=warnings;self.information=information;self.hints=hints}
    public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["errors","warnings","information","hints"],path:"diagnostics");errors=try c.decode(UInt32.self,forKey:.errors);warnings=try c.decode(UInt32.self,forKey:.warnings);information=try c.decode(UInt32.self,forKey:.information);hints=try c.decode(UInt32.self,forKey:.hints);guard [errors,warnings,information,hints].allSatisfy({$0<=1_000_000}) else{throw OctetDecodeError.invalidValue(path:"diagnostics",message:"count exceeds limit")}}
}

public struct LspServerStatus: Codable, Equatable, Sendable {
    public let projectId:RuntimeId;public let languageId:RuntimeId;public let state:LspServerState;public let restartCount:UInt32;public let configuredAtMs:UInt64;public let updatedAtMs:UInt64;public let diagnosticRevision:UInt64;public let diagnostics:DiagnosticCounts;public let failure:String?
    private enum CodingKeys:String,CodingKey{case projectId,languageId,state,restartCount,configuredAtMs,updatedAtMs,diagnosticRevision,diagnostics,failure}
    public init(projectId:RuntimeId,languageId:RuntimeId,state:LspServerState,restartCount:UInt32,configuredAtMs:UInt64,updatedAtMs:UInt64,diagnosticRevision:UInt64,diagnostics:DiagnosticCounts,failure:String?=nil){self.projectId=projectId;self.languageId=languageId;self.state=state;self.restartCount=restartCount;self.configuredAtMs=configuredAtMs;self.updatedAtMs=updatedAtMs;self.diagnosticRevision=diagnosticRevision;self.diagnostics=diagnostics;self.failure=failure}
    public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["projectId","languageId","state","restartCount","configuredAtMs","updatedAtMs","diagnosticRevision","diagnostics","failure"],path:"lspServer");projectId=try c.decode(RuntimeId.self,forKey:.projectId);languageId=try c.decode(RuntimeId.self,forKey:.languageId);state=try c.decode(LspServerState.self,forKey:.state);restartCount=try c.decode(UInt32.self,forKey:.restartCount);configuredAtMs=try c.decode(UInt64.self,forKey:.configuredAtMs);updatedAtMs=try c.decode(UInt64.self,forKey:.updatedAtMs);diagnosticRevision=try c.decode(UInt64.self,forKey:.diagnosticRevision);diagnostics=try c.decode(DiagnosticCounts.self,forKey:.diagnostics);failure=try c.decodeIfPresent(String.self,forKey:.failure);if let failure{_=try runtimeText(failure,path:"lspServer.failure",limit:2048)}}
}

public struct ContextCategoryTotal: Codable, Equatable, Sendable { public let category:ContextCategory;public let tokens:UInt64; private enum CodingKeys:String,CodingKey{case category,tokens}; public init(category:ContextCategory,tokens:UInt64){self.category=category;self.tokens=tokens};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["category","tokens"],path:"contextCategory");category=try c.decode(ContextCategory.self,forKey:.category);tokens=try c.decode(UInt64.self,forKey:.tokens)} }
public struct ContextTotals: Codable, Equatable, Sendable {
    public let categories: [ContextCategoryTotal]
    public let totalTokens: UInt64
    private enum CodingKeys: String, CodingKey { case categories, totalTokens }
    public init(categories: [ContextCategoryTotal], totalTokens: UInt64) throws {
        guard categories.count <= 16 else { throw OctetDecodeError.invalidValue(path: "contextTotals.categories", message: "too many categories") }
        var seen = Set<ContextCategory>()
        var sum: UInt64 = 0
        for item in categories {
            guard seen.insert(item.category).inserted else { throw OctetDecodeError.invalidValue(path: "contextTotals.categories", message: "duplicate category") }
            let result = sum.addingReportingOverflow(item.tokens)
            guard !result.overflow else { throw OctetDecodeError.invalidValue(path: "contextTotals", message: "token sum overflow") }
            sum = result.partialValue
        }
        guard sum == totalTokens else { throw OctetDecodeError.invalidValue(path: "contextTotals", message: "total does not match categories") }
        self.categories = categories
        self.totalTokens = totalTokens
    }
    public init(from decoder: Decoder) throws {
        let c = try strictContainer(decoder, keys: CodingKeys.self, allowed: ["categories", "totalTokens"], path: "contextTotals")
        try self.init(categories: c.decode([ContextCategoryTotal].self, forKey: .categories), totalTokens: c.decode(UInt64.self, forKey: .totalTokens))
    }
}

public struct ActiveCompaction: Codable, Equatable, Sendable { public let id:RuntimeId;public let reason:ContextCompactionReason;public let before:ContextTotals;public let startedAtMs:UInt64;private enum CodingKeys:String,CodingKey{case id,reason,before,startedAtMs};public init(id:RuntimeId,reason:ContextCompactionReason,before:ContextTotals,startedAtMs:UInt64){self.id=id;self.reason=reason;self.before=before;self.startedAtMs=startedAtMs};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["id","reason","before","startedAtMs"],path:"activeCompaction");id=try c.decode(RuntimeId.self,forKey:.id);reason=try c.decode(ContextCompactionReason.self,forKey:.reason);before=try c.decode(ContextTotals.self,forKey:.before);startedAtMs=try c.decode(UInt64.self,forKey:.startedAtMs)}}
public struct CompletedCompaction: Codable, Equatable, Sendable { public let id:RuntimeId;public let reason:ContextCompactionReason;public let before:ContextTotals;public let after:ContextTotals;public let reclaimedTokens:UInt64;public let succeeded:Bool;public let startedAtMs:UInt64;public let finishedAtMs:UInt64;private enum CodingKeys:String,CodingKey{case id,reason,before,after,reclaimedTokens,succeeded,startedAtMs,finishedAtMs};public init(id:RuntimeId,reason:ContextCompactionReason,before:ContextTotals,after:ContextTotals,reclaimedTokens:UInt64,succeeded:Bool,startedAtMs:UInt64,finishedAtMs:UInt64){self.id=id;self.reason=reason;self.before=before;self.after=after;self.reclaimedTokens=reclaimedTokens;self.succeeded=succeeded;self.startedAtMs=startedAtMs;self.finishedAtMs=finishedAtMs};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["id","reason","before","after","reclaimedTokens","succeeded","startedAtMs","finishedAtMs"],path:"completedCompaction");id=try c.decode(RuntimeId.self,forKey:.id);reason=try c.decode(ContextCompactionReason.self,forKey:.reason);before=try c.decode(ContextTotals.self,forKey:.before);after=try c.decode(ContextTotals.self,forKey:.after);reclaimedTokens=try c.decode(UInt64.self,forKey:.reclaimedTokens);succeeded=try c.decode(Bool.self,forKey:.succeeded);startedAtMs=try c.decode(UInt64.self,forKey:.startedAtMs);finishedAtMs=try c.decode(UInt64.self,forKey:.finishedAtMs)}}
public struct ContextStatus: Codable, Equatable, Sendable { public let current:ContextTotals;public let updatedAtMs:UInt64;public let activeCompaction:ActiveCompaction?;public let lastCompaction:CompletedCompaction?;private enum CodingKeys:String,CodingKey{case current,updatedAtMs,activeCompaction,lastCompaction};public init(current:ContextTotals,updatedAtMs:UInt64,activeCompaction:ActiveCompaction?=nil,lastCompaction:CompletedCompaction?=nil){self.current=current;self.updatedAtMs=updatedAtMs;self.activeCompaction=activeCompaction;self.lastCompaction=lastCompaction};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["current","updatedAtMs","activeCompaction","lastCompaction"],path:"context");current=try c.decode(ContextTotals.self,forKey:.current);updatedAtMs=try c.decode(UInt64.self,forKey:.updatedAtMs);activeCompaction=try c.decodeIfPresent(ActiveCompaction.self,forKey:.activeCompaction);lastCompaction=try c.decodeIfPresent(CompletedCompaction.self,forKey:.lastCompaction)}}

public struct RuntimePolicyStatus: Codable, Equatable, Sendable { public let revision:UInt64;public let observedAtMs:UInt64;public let filesystem:FilesystemPolicy;public let tools:ToolPolicy;public let commands:CommandPolicy;public let remoteRead:RemoteReadPolicy;public let processNetwork:ProcessNetworkPolicy;public let approvals:ApprovalPolicy;public let secrets:SecretsPolicy;private enum CodingKeys:String,CodingKey{case revision,observedAtMs,filesystem,tools,commands,remoteRead,processNetwork,approvals,secrets};public init(revision:UInt64,observedAtMs:UInt64,filesystem:FilesystemPolicy,tools:ToolPolicy,commands:CommandPolicy,remoteRead:RemoteReadPolicy,processNetwork:ProcessNetworkPolicy,approvals:ApprovalPolicy,secrets:SecretsPolicy){self.revision=revision;self.observedAtMs=observedAtMs;self.filesystem=filesystem;self.tools=tools;self.commands=commands;self.remoteRead=remoteRead;self.processNetwork=processNetwork;self.approvals=approvals;self.secrets=secrets};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["revision","observedAtMs","filesystem","tools","commands","remoteRead","processNetwork","approvals","secrets"],path:"policy");revision=try c.decode(UInt64.self,forKey:.revision);observedAtMs=try c.decode(UInt64.self,forKey:.observedAtMs);filesystem=try c.decode(FilesystemPolicy.self,forKey:.filesystem);tools=try c.decode(ToolPolicy.self,forKey:.tools);commands=try c.decode(CommandPolicy.self,forKey:.commands);remoteRead=try c.decode(RemoteReadPolicy.self,forKey:.remoteRead);processNetwork=try c.decode(ProcessNetworkPolicy.self,forKey:.processNetwork);approvals=try c.decode(ApprovalPolicy.self,forKey:.approvals);secrets=try c.decode(SecretsPolicy.self,forKey:.secrets)}}

public struct RuntimeSnapshot: Codable, Equatable, Sendable { public let childAgents:[ChildAgentStatus];public let mcpServers:[McpServerStatus];public let catalog:TrustedCatalogStatus;public let lspServers:[LspServerStatus];public let context:ContextStatus;public let policy:RuntimePolicyStatus?;private enum CodingKeys:String,CodingKey{case childAgents,mcpServers,catalog,lspServers,context,policy};public init(childAgents:[ChildAgentStatus],mcpServers:[McpServerStatus],catalog:TrustedCatalogStatus,lspServers:[LspServerStatus],context:ContextStatus,policy:RuntimePolicyStatus?=nil)throws{guard childAgents.count<=512,mcpServers.count<=128,lspServers.count<=256 else{throw OctetDecodeError.invalidValue(path:"runtimeSnapshot",message:"collection exceeds limit")};self.childAgents=childAgents;self.mcpServers=mcpServers;self.catalog=catalog;self.lspServers=lspServers;self.context=context;self.policy=policy};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["childAgents","mcpServers","catalog","lspServers","context","policy"],path:"runtimeSnapshot");try self.init(childAgents:c.decode([ChildAgentStatus].self,forKey:.childAgents),mcpServers:c.decode([McpServerStatus].self,forKey:.mcpServers),catalog:c.decode(TrustedCatalogStatus.self,forKey:.catalog),lspServers:c.decode([LspServerStatus].self,forKey:.lspServers),context:c.decode(ContextStatus.self,forKey:.context),policy:c.decodeIfPresent(RuntimePolicyStatus.self,forKey:.policy))}}
