import Foundation

public enum SessionOwner: String, Codable, Equatable, Sendable { case user, agent, host }
public enum EventKind: String, Codable, Equatable, Sendable { case snapshot, session, runtime, notification }
public enum CommandKind: String, Codable, Equatable, Sendable { case host, session }
public enum CommandStatus: String, Codable, Equatable, Sendable { case accepted, rejected, completed, failed }
public enum CommandErrorCode: String, Codable, Equatable, Sendable { case unauthorized, forbidden, notFound, invalid, conflict, unavailable, replayGap, revoked, rateLimited, internalError }
public enum PromptKind: String, Codable, Equatable, Sendable { case approval, question, confirmation, secret }
public enum PromptResponseKind: String, Codable, Equatable, Sendable { case answer, approve, reject, cancel }
public enum SessionItemRole: String, Codable, Equatable, Sendable { case system, user, assistant, tool }
public enum SessionItemState: String, Codable, Equatable, Sendable { case pending, streaming, complete, failed, cancelled }
public enum ToolCallState: String, Codable, Equatable, Sendable { case pending, running, succeeded, failed, cancelled }
public enum DiffLineKind: String, Codable, Equatable, Sendable { case context, addition, deletion }
public enum DocumentKind: String, Codable, Equatable, Sendable { case markdown, text, code, json }
public enum FileEntryKind: String, Codable, Equatable, Sendable { case file, directory, symlink }
public enum ThemeKind: String, Codable, Equatable, Sendable { case dark, light, system }

// Runtime projection enums mirror `runtime_status.rs`.
public enum ChildAgentState: String, Codable, Equatable, Sendable { case queued, running, waiting, succeeded, failed, cancelled }
public enum McpServerState: String, Codable, Equatable, Sendable { case configured, starting, ready, failed, stopped }
public enum TrustedCatalogKind: String, Codable, Equatable, Sendable { case skill, `extension` }
public enum ContributionKind: String, Codable, Equatable, Sendable { case skill, tool, command, mcpServer, theme, languageServer }
public enum LspServerState: String, Codable, Equatable, Sendable { case configured, starting, ready, failed, stopped }
public enum ContextCategory: String, Codable, Equatable, Hashable, Sendable { case system, projectInstructions, conversation, toolResults, attachments, documents, projectFiles, compactionSummaries, other }
public enum ContextCompactionReason: String, Codable, Equatable, Sendable { case threshold, overflow }
public enum RuleDefault: String, Codable, Equatable, Sendable { case allow, deny }
public enum UnavailableConsequence: String, Codable, Equatable, Sendable { case featureBlocked, hostBehaviorUnknown }
public enum FilesystemAccess: String, Codable, Equatable, Sendable { case none, trustedProjectRead, trustedProjectReadWrite }
public enum ApprovalOperation: String, Codable, Equatable, Comparable, Sendable {
    case filesystemWrite, tool, command, remoteRead, processNetwork, secretAccess
    // A `String` raw type blocks synthesized `Comparable`; declaration order mirrors
    // `runtime_status.rs` (`#[derive(PartialOrd, Ord)]`) so the ordering stays wire-identical.
    private static let canonicalOrder: [ApprovalOperation] = [.filesystemWrite, .tool, .command, .remoteRead, .processNetwork, .secretAccess]
    public static func < (lhs: ApprovalOperation, rhs: ApprovalOperation) -> Bool {
        let left = canonicalOrder.firstIndex(of: lhs) ?? canonicalOrder.count
        let right = canonicalOrder.firstIndex(of: rhs) ?? canonicalOrder.count
        return left < right
    }
}

public enum FilesystemPolicy: Codable, Equatable, Sendable {
    case enforced(access: FilesystemAccess)
    case unavailable(reason: String, consequence: UnavailableConsequence)
    private enum CodingKeys: String, CodingKey { case status, access, reason, consequence }
    public init(from decoder: Decoder) throws { let c = try strictContainer(decoder, keys: CodingKeys.self, allowed: ["status", "access", "reason", "consequence"], path: "filesystemPolicy"); switch try c.decode(String.self, forKey: .status) { case "enforced": self = .enforced(access: try c.decode(FilesystemAccess.self, forKey: .access)); case "unavailable": self = .unavailable(reason: try c.decode(String.self, forKey: .reason), consequence: try c.decode(UnavailableConsequence.self, forKey: .consequence)); default: throw OctetDecodeError.invalidValue(path: "filesystemPolicy.status", message: "unknown status") } }
    public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case let .enforced(access): try c.encode("enforced", forKey: .status); try c.encode(access, forKey: .access); case let .unavailable(reason, consequence): try c.encode("unavailable", forKey: .status); try c.encode(reason, forKey: .reason); try c.encode(consequence, forKey: .consequence) } }
}

public struct RuntimeRuleSet<Value: Codable & Equatable & Sendable>: Codable, Equatable, Sendable {
    public let `default`: RuleDefault; public let allow: [Value]; public let deny: [Value]
    private enum CodingKeys: String, CodingKey { case `default`, allow, deny }
    public init(default defaultValue: RuleDefault, allow: [Value], deny: [Value]) { self.default = defaultValue; self.allow = allow; self.deny = deny }
    public init(from decoder: Decoder) throws { let c = try strictContainer(decoder, keys: CodingKeys.self, allowed: ["default", "allow", "deny"], path: "rules"); `default`=try c.decode(RuleDefault.self,forKey:.default); allow=try c.decode([Value].self,forKey:.allow); deny=try c.decode([Value].self,forKey:.deny) }
}

public enum ToolPolicy: Codable, Equatable, Sendable { case enforced(rules: RuntimeRuleSet<RuntimeId>); case unavailable(reason: String, consequence: UnavailableConsequence); private enum CodingKeys: String, CodingKey { case status, rules, reason, consequence }; public init(from decoder: Decoder) throws { let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["status","rules","reason","consequence"],path:"toolPolicy"); switch try c.decode(String.self,forKey:.status) { case "enforced": self = .enforced(rules:try c.decode(RuntimeRuleSet<RuntimeId>.self,forKey:.rules)); case "unavailable": self = .unavailable(reason:try c.decode(String.self,forKey:.reason),consequence:try c.decode(UnavailableConsequence.self,forKey:.consequence)); default: throw OctetDecodeError.invalidValue(path:"toolPolicy.status",message:"unknown status") } }; public func encode(to encoder: Encoder) throws { var c=encoder.container(keyedBy:CodingKeys.self); switch self { case let .enforced(rules):try c.encode("enforced",forKey:.status);try c.encode(rules,forKey:.rules); case let .unavailable(reason,consequence):try c.encode("unavailable",forKey:.status);try c.encode(reason,forKey:.reason);try c.encode(consequence,forKey:.consequence) } } }

public struct CommandName: Codable, Equatable, Hashable, Sendable { public let value: String; public init(_ value: String) throws { try requireNonEmpty(value,path:"commandName"); guard value.utf8.allSatisfy({ $0 == 45 || $0 == 46 || $0 == 95 || $0 == 43 || (48...57).contains($0) || (65...90).contains($0) || (97...122).contains($0) }) else { throw OctetDecodeError.invalidValue(path:"commandName",message:"invalid command name") }; self.value=value }; public init(from decoder: Decoder) throws { try self.init(decoder.singleValueContainer().decode(String.self)) }; public func encode(to encoder: Encoder) throws { var c=encoder.singleValueContainer(); try c.encode(value) } }
public struct DomainName: Codable, Equatable, Hashable, Sendable { public let value: String; public init(_ value: String) throws { try requireNonEmpty(value,path:"domainName",limit:253); guard value == value.lowercased(), !value.contains(".."), value.split(separator:".").allSatisfy({ !$0.isEmpty && !$0.hasPrefix("-") && !$0.hasSuffix("-") && $0.allSatisfy({ $0.isLetter || $0.isNumber || $0 == "-" }) }) else { throw OctetDecodeError.invalidValue(path:"domainName",message:"invalid domain") }; self.value=value }; public init(from decoder: Decoder) throws { try self.init(decoder.singleValueContainer().decode(String.self)) }; public func encode(to encoder: Encoder) throws { var c=encoder.singleValueContainer(); try c.encode(value) } }

public enum CommandPolicy: Codable, Equatable, Sendable { case enforced(rules: RuntimeRuleSet<CommandName>); case unavailable(reason: String, consequence: UnavailableConsequence); private enum CodingKeys: String, CodingKey { case status, rules, reason, consequence }; public init(from decoder: Decoder) throws { let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["status","rules","reason","consequence"],path:"commandPolicy"); switch try c.decode(String.self,forKey:.status) { case "enforced":self = .enforced(rules:try c.decode(RuntimeRuleSet<CommandName>.self,forKey:.rules)); case "unavailable":self = .unavailable(reason:try c.decode(String.self,forKey:.reason),consequence:try c.decode(UnavailableConsequence.self,forKey:.consequence)); default:throw OctetDecodeError.invalidValue(path:"commandPolicy.status",message:"unknown status") } }; public func encode(to encoder: Encoder) throws { var c=encoder.container(keyedBy:CodingKeys.self); switch self { case let .enforced(rules):try c.encode("enforced",forKey:.status);try c.encode(rules,forKey:.rules); case let .unavailable(reason,consequence):try c.encode("unavailable",forKey:.status);try c.encode(reason,forKey:.reason);try c.encode(consequence,forKey:.consequence) } } }

public enum RemoteReadConsequence: Codable, Equatable, Sendable { case blocked; case domainRules(domains: RuntimeRuleSet<DomainName>); private enum CodingKeys: String, CodingKey { case mode, domains }; public init(from decoder: Decoder) throws { let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["mode","domains"],path:"remoteReadConsequence"); switch try c.decode(String.self,forKey:.mode) { case "blocked":self = .blocked; case "domainRules":self = .domainRules(domains:try c.decode(RuntimeRuleSet<DomainName>.self,forKey:.domains)); default:throw OctetDecodeError.invalidValue(path:"remoteReadConsequence.mode",message:"unknown mode") } }; public func encode(to encoder: Encoder) throws { var c=encoder.container(keyedBy:CodingKeys.self); switch self { case .blocked:try c.encode("blocked",forKey:.mode); case let .domainRules(domains):try c.encode("domainRules",forKey:.mode);try c.encode(domains,forKey:.domains) } } }
public enum RemoteReadPolicy: Codable, Equatable, Sendable { case enforced(consequence: RemoteReadConsequence); case unavailable(reason: String, consequence: UnavailableConsequence); private enum CodingKeys: String, CodingKey { case status, consequence, reason }; public init(from decoder: Decoder) throws { let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["status","consequence","reason"],path:"remoteReadPolicy"); switch try c.decode(String.self,forKey:.status) { case "enforced":self = .enforced(consequence:try c.decode(RemoteReadConsequence.self,forKey:.consequence)); case "unavailable":self = .unavailable(reason:try c.decode(String.self,forKey:.reason),consequence:try c.decode(UnavailableConsequence.self,forKey:.consequence)); default:throw OctetDecodeError.invalidValue(path:"remoteReadPolicy.status",message:"unknown status") } }; public func encode(to encoder: Encoder) throws { var c=encoder.container(keyedBy:CodingKeys.self); switch self { case let .enforced(consequence):try c.encode("enforced",forKey:.status);try c.encode(consequence,forKey:.consequence); case let .unavailable(reason,consequence):try c.encode("unavailable",forKey:.status);try c.encode(reason,forKey:.reason);try c.encode(consequence,forKey:.consequence) } } }
public typealias ProcessNetworkConsequence = RemoteReadConsequence
public typealias ProcessNetworkPolicy = RemoteReadPolicy

public enum ApprovalConsequence: Codable, Equatable, Sendable { case never; case requiredFor(operations:[ApprovalOperation]); private enum CodingKeys:String,CodingKey {case mode,operations}; public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["mode","operations"],path:"approvalConsequence");switch try c.decode(String.self,forKey:.mode){case "never":self = .never;case "requiredFor":self = .requiredFor(operations:try c.decode([ApprovalOperation].self,forKey:.operations));default:throw OctetDecodeError.invalidValue(path:"approvalConsequence.mode",message:"unknown mode")}};public func encode(to encoder:Encoder)throws{var c=encoder.container(keyedBy:CodingKeys.self);switch self{case .never:try c.encode("never",forKey:.mode);case let .requiredFor(operations):try c.encode("requiredFor",forKey:.mode);try c.encode(operations,forKey:.operations)}}}
public enum ApprovalPolicy: Codable, Equatable, Sendable { case enforced(consequence:ApprovalConsequence);case unavailable(reason:String,consequence:UnavailableConsequence);private enum CodingKeys:String,CodingKey{case status,consequence,reason};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["status","consequence","reason"],path:"approvalPolicy");switch try c.decode(String.self,forKey:.status){case "enforced":self = .enforced(consequence:try c.decode(ApprovalConsequence.self,forKey:.consequence));case "unavailable":self = .unavailable(reason:try c.decode(String.self,forKey:.reason),consequence:try c.decode(UnavailableConsequence.self,forKey:.consequence));default:throw OctetDecodeError.invalidValue(path:"approvalPolicy.status",message:"unknown status")}};public func encode(to encoder:Encoder)throws{var c=encoder.container(keyedBy:CodingKeys.self);switch self{case let .enforced(consequence):try c.encode("enforced",forKey:.status);try c.encode(consequence,forKey:.consequence);case let .unavailable(reason,consequence):try c.encode("unavailable",forKey:.status);try c.encode(reason,forKey:.reason);try c.encode(consequence,forKey:.consequence)}}}

public enum SecretsConsequence: Codable, Equatable, Sendable { case blocked;case namedGrants(grants:[RuntimeId]);private enum CodingKeys:String,CodingKey{case mode,grants};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["mode","grants"],path:"secretsConsequence");switch try c.decode(String.self,forKey:.mode){case "blocked":self = .blocked;case "namedGrants":self = .namedGrants(grants:try c.decode([RuntimeId].self,forKey:.grants));default:throw OctetDecodeError.invalidValue(path:"secretsConsequence.mode",message:"unknown mode")}};public func encode(to encoder:Encoder)throws{var c=encoder.container(keyedBy:CodingKeys.self);switch self{case .blocked:try c.encode("blocked",forKey:.mode);case let .namedGrants(grants):try c.encode("namedGrants",forKey:.mode);try c.encode(grants,forKey:.grants)}}}
public enum SecretsPolicy: Codable, Equatable, Sendable {case enforced(consequence:SecretsConsequence);case unavailable(reason:String,consequence:UnavailableConsequence);private enum CodingKeys:String,CodingKey{case status,consequence,reason};public init(from decoder:Decoder)throws{let c=try strictContainer(decoder,keys:CodingKeys.self,allowed:["status","consequence","reason"],path:"secretsPolicy");switch try c.decode(String.self,forKey:.status){case "enforced":self = .enforced(consequence:try c.decode(SecretsConsequence.self,forKey:.consequence));case "unavailable":self = .unavailable(reason:try c.decode(String.self,forKey:.reason),consequence:try c.decode(UnavailableConsequence.self,forKey:.consequence));default:throw OctetDecodeError.invalidValue(path:"secretsPolicy.status",message:"unknown status")}};public func encode(to encoder:Encoder)throws{var c=encoder.container(keyedBy:CodingKeys.self);switch self{case let .enforced(consequence):try c.encode("enforced",forKey:.status);try c.encode(consequence,forKey:.consequence);case let .unavailable(reason,consequence):try c.encode("unavailable",forKey:.status);try c.encode(reason,forKey:.reason);try c.encode(consequence,forKey:.consequence)}}}
