"""Pinned modern MCP wire/adversarial fixtures; no live MCP services are used."""

from __future__ import annotations

import copy
from dataclasses import replace
import threading
import time
import unittest
from unittest.mock import patch

from octet_mcp.catalog import CatalogError, normalize_schema
from octet_mcp.http_2026 import McpHttp2026Client
from octet_mcp.protocol import McpCancelled, McpError, McpProtocolError
from octet_mcp.protocol_2026 import (
    MCP_PROTOCOL_VERSION_2026,
    MAX_MIRRORED_HEADER_BYTES,
    MAX_SAFE_INTEGER,
    McpModernRemoteError,
    encode_header_value,
    header_parameters,
    request_headers,
)
from octet_mcp.streamable_http import McpStreamableHttpClient

from .helpers import FakeCancellation, limits
from .test_streamable_http import (
    _HttpReply,
    _LoopbackFixture,
    _json_bytes,
    _json_result,
    _remote_config,
    _sse_event,
    _tool,
)


# Exact standard metadata, kept literal rather than generated by implementation.
METADATA = {
    "io.modelcontextprotocol/protocolVersion": "2026-07-28",
    "io.modelcontextprotocol/clientInfo": {"name": "octet-mcp", "version": "0.7.3"},
    "io.modelcontextprotocol/clientCapabilities": {},
}
DISCOVERY = {
    "resultType": "complete",
    "supportedVersions": ["2026-07-28"],
    "capabilities": {"tools": {}},
    "_meta": {"io.modelcontextprotocol/serverInfo": {"name": "fixture", "version": "1.0"}},
}


def annotated_tool():
    tool = _tool()
    tool["inputSchema"]["properties"]["value"]["x-mcp-header"] = "Value"
    return tool


def error_reply(request, code, *, status=400, data=None, request_id=None):
    error = {"code": code, "message": "UNTRUSTED secret remote error"}
    if data is not None:
        error["data"] = data
    return _HttpReply(
        status=status, headers={"Content-Type": "application/json"},
        body=_json_bytes({"jsonrpc": "2.0", "id": request.message()["id"] if request_id is None else request_id, "error": error}),
    )


class HeaderMetadataTests(unittest.TestCase):
    def test_exact_spec_header_encoding_examples(self):
        for value, expected in (
            ("us-west1", "us-west1"),
            ("Hello, 世界", "=?base64?SGVsbG8sIOS4lueVjA==?="),
            (" padded ", "=?base64?IHBhZGRlZCA=?="),
            ("line1\nline2", "=?base64?bGluZTEKbGluZTI=?="),
            ("=?base64?literal?=", "=?base64?PT9iYXNlNjQ/bGl0ZXJhbD89?="),
            ("", ""), ("a\tb", "a\tb"), ("\tx", "=?base64?CXg=?="),
        ):
            with self.subTest(value=value):
                self.assertEqual(encode_header_value(value), expected)

    def test_nested_primitive_extraction_null_omission_and_safe_integers(self):
        parameters = header_parameters({"properties": {"nested": {"properties": {
            "s": {"type": "string", "x-mcp-header": "S"},
            "n": {"type": "integer", "x-mcp-header": "N"},
            "b": {"type": "boolean", "x-mcp-header": "B"},
        }}}})
        headers = request_headers("tools/call", {"name": " t ", "arguments": {"nested": {"s": None, "n": 42.0, "b": False}}}, parameters)
        self.assertEqual(headers, {
            "MCP-Protocol-Version": "2026-07-28", "Mcp-Method": "tools/call",
            "Mcp-Name": "=?base64?IHQg?=", "Mcp-Param-N": "42", "Mcp-Param-B": "false",
        })
        for value in (MAX_SAFE_INTEGER + 1, -MAX_SAFE_INTEGER - 1, True, 1.5, "4"):
            with self.subTest(value=value), self.assertRaises(McpProtocolError):
                request_headers("tools/call", {"name": "t", "arguments": {"nested": {"n": value}}}, parameters)
        self.assertNotIn("Mcp-Param-S", request_headers("tools/call", {"name": "t", "arguments": {}}, parameters))

    def test_header_annotations_reject_unsafe_names_types_and_reachability(self):
        leaf = {"type": "string", "x-mcp-header": "Tenant"}
        schemas = [
            leaf,
            {"properties": {"x": {**leaf, "x-mcp-header": "bad\r\nInjected"}}},
            {"properties": {"x": {**leaf, "x-mcp-header": ""}}},
            {"properties": {"x": {**leaf, "type": "number"}}},
            {"properties": {"x": {**leaf, "type": ["string", "null"]}}},
            {"properties": {"x": leaf, "y": {**leaf, "x-mcp-header": "tenant"}}},
            {"properties": {"x": {"items": {"properties": {"y": leaf}}}}},
            {"allOf": [{"properties": {"x": leaf}}]},
            {"additionalProperties": {"properties": {"x": leaf}}},
            {"$defs": {"x": leaf}, "properties": {"x": {"$ref": "#/$defs/x"}}},
            {"$defs": {"unused": {"properties": {"x": leaf}}}},
        ]
        for schema in schemas:
            with self.subTest(schema=schema), self.assertRaises(CatalogError):
                header_parameters(schema)
        # Literal annotation-looking data in enum/const is not a schema node.
        self.assertEqual(header_parameters({"properties": {"x": {"const": {"x-mcp-header": "data"}}}}), ())

    def test_header_value_and_aggregate_budgets_reject_without_truncation(self):
        with self.assertRaises(McpProtocolError):
            encode_header_value("x" * (MAX_MIRRORED_HEADER_BYTES + 1))
        parameters = header_parameters({"properties": {
            "a": {"type": "string", "x-mcp-header": "A"},
            "b": {"type": "string", "x-mcp-header": "B"},
        }})
        with self.assertRaises(McpProtocolError):
            request_headers("tools/call", {"name": "t", "arguments": {"a": "a" * 9000, "b": "b" * 9000}}, parameters)

    def test_ref_sibling_headers_retain_raw_and_published_provenance(self):
        schema = {
            "properties": {"value": {
                "$ref": "#/$defs/bounded", "type": "string", "x-mcp-header": "Value",
                "allOf": [{"minLength": 1}],
            }},
            "$defs": {"bounded": {"type": "string", "maxLength": 3}},
        }
        self.assertEqual(header_parameters(schema), header_parameters(normalize_schema(schema, require_object=True)))
        # A $ref cannot erase an invalid original placement or duplicate name.
        for bad in (
            {"$defs": {"hidden": {"properties": {"x": {"type": "string", "x-mcp-header": "X"}}}}, "$ref": "#/$defs/hidden"},
            {"properties": {"a": {"type": "string", "x-mcp-header": "X"}, "nested": {"properties": {"b": {"type": "string", "x-mcp-header": "x"}}}}},
        ):
            with self.assertRaises(CatalogError):
                header_parameters(bad)

    def test_header_count_budget_and_prefix_cannot_override_protocol_or_credentials(self):
        with self.assertRaises(CatalogError):
            header_parameters({"properties": {f"p{i}": {"type": "string", "x-mcp-header": f"P{i}"} for i in range(62)}})
        parameters = header_parameters({"properties": {"value": {"type": "string", "x-mcp-header": "Authorization"}}})
        headers = request_headers("tools/call", {"name": "echo", "arguments": {"value": "untrusted"}}, parameters)
        self.assertNotIn("Authorization", headers)
        self.assertEqual(headers["Mcp-Param-Authorization"], "untrusted")
        self.assertEqual(headers["MCP-Protocol-Version"], "2026-07-28")


class ModernHttpTests(unittest.TestCase):
    def setUp(self):
        self.fixtures = []
        self.clients = []

    def tearDown(self):
        for client in reversed(self.clients):
            client.close()
        for fixture in reversed(self.fixtures):
            fixture.close()
            self.assertEqual(fixture.errors, ())

    def client(self, responder, *, config_changes=None, bridge_limits=None, **kwargs):
        fixture = _LoopbackFixture(responder)
        self.fixtures.append(fixture)
        config = replace(_remote_config(fixture.url), protocol_version=MCP_PROTOCOL_VERSION_2026, **(config_changes or {}))
        client = McpHttp2026Client(config, bridge_limits or limits(), **kwargs)
        self.clients.append(client)
        return client, fixture

    def responder(self, tool_reply=None, *, tools=None, discovery=None):
        def respond(request):
            message = request.message()
            if message["method"] == "server/discover":
                return _json_result(request, DISCOVERY if discovery is None else discovery)
            if message["method"] == "tools/list":
                return _json_result(request, {"resultType": "complete", "tools": tools if tools is not None else [annotated_tool()]})
            if message["method"] == "tools/call" and tool_reply is not None:
                return tool_reply(request)
            raise AssertionError("unexpected modern request")
        return respond

    def test_explicit_mode_is_required_and_legacy_constants_are_unchanged(self):
        from octet_mcp.protocol import MCP_PROTOCOL_VERSION, SUPPORTED_PROTOCOL_VERSIONS
        self.assertEqual(MCP_PROTOCOL_VERSION, "2025-06-18")
        self.assertNotIn(MCP_PROTOCOL_VERSION_2026, SUPPORTED_PROTOCOL_VERSIONS)
        with self.assertRaises(ValueError):
            McpHttp2026Client(_remote_config("http://127.0.0.1:1/mcp"), limits())
        self.assertTrue(issubclass(McpHttp2026Client, McpStreamableHttpClient))

    def test_exact_discovery_list_call_wire_and_no_session_lifecycle(self):
        tool = annotated_tool()
        tool["name"] = "天气"
        client, fixture = self.client(self.responder(
            lambda request: _json_result(request, {"resultType": "complete", "content": [{"type": "text", "text": "ok"}]}), tools=[tool]
        ))
        client.start()
        self.assertEqual(client.server_info, {"name": "fixture", "version": "1.0"})
        client.list_tools()
        client.call_tool("天气", {"value": "line1\nline2"})
        client.close()
        messages = [request.message() for request in fixture.requests]
        self.assertEqual(messages[0], {"jsonrpc": "2.0", "id": 1, "method": "server/discover", "params": {"_meta": METADATA}})
        self.assertEqual(messages[1], {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {"_meta": METADATA}})
        self.assertEqual(messages[2], {"jsonrpc": "2.0", "id": 3, "method": "tools/call", "params": {
            "name": "天气", "arguments": {"value": "line1\nline2"}, "_meta": {**METADATA, "progressToken": "octet-mcp:3"},
        }})
        for request in fixture.requests:
            self.assertEqual(request.method, "POST")
            self.assertEqual(request.header("MCP-Protocol-Version"), "2026-07-28")
            self.assertEqual(request.header("Mcp-Method"), request.message()["method"])
            self.assertEqual(request.header("Accept"), "application/json, text/event-stream")
            self.assertIsNone(request.header("Mcp-Session-Id"))
            self.assertIsNone(request.header("Last-Event-ID"))
        self.assertEqual(fixture.requests[-1].header("Mcp-Name"), "=?base64?5aSp5rCU?=")
        self.assertEqual(fixture.requests[-1].header("Mcp-Param-Value"), "=?base64?bGluZTEKbGluZTI=?=")

    def test_discovery_negotiation_errors_do_not_downgrade_or_reprobe(self):
        for status in (200, 400):
            client, fixture = self.client(lambda request: error_reply(request, -32022, status=status, data={"supported": ["2025-06-18"], "requested": "2026-07-28"}))
            with self.assertRaises(McpModernRemoteError) as error:
                client.start()
            self.assertEqual(error.exception.supported_versions, ("2025-06-18",))
            self.assertNotIn("UNTRUSTED", str(error.exception))
            self.assertEqual([request.message()["method"] for request in fixture.requests], ["server/discover"])

    def test_negotiation_header_and_capability_errors_never_replay_tools(self):
        for code in (-32020, -32021, -32022):
            for status in (200, 400):
                client, fixture = self.client(self.responder(lambda request: error_reply(request, code, status=status, data={"supported": ["2026-07-28"]})))
                client.start()
                client.list_tools()
                with self.assertRaises(McpModernRemoteError):
                    client.call_tool("echo", {"value": "side-effect"})
                self.assertEqual([request.message()["method"] for request in fixture.requests], ["server/discover", "tools/list", "tools/call"])

    def test_invalid_discovery_and_foreign_error_ids_fail_closed(self):
        variants = [
            {**DISCOVERY, "supportedVersions": []},
            {**DISCOVERY, "supportedVersions": ["2025-06-18"]},
            {**DISCOVERY, "supportedVersions": [True]},
            {**DISCOVERY, "capabilities": {"tools": True}},
            {**DISCOVERY, "_meta": {"io.modelcontextprotocol/serverInfo": "bad"}},
        ]
        for value in variants:
            client, fixture = self.client(self.responder(discovery=value))
            with self.assertRaises(McpProtocolError):
                client.start()
            self.assertEqual(len(fixture.requests), 1)
        client, fixture = self.client(lambda request: error_reply(request, -32022, request_id="foreign", data={"supported": ["2025-06-18"]}))
        with self.assertRaises(McpProtocolError):
            client.start()
        self.assertEqual(len(fixture.requests), 1)

    def test_invalid_header_tools_are_excluded_with_an_explicit_warning(self):
        bad = annotated_tool()
        bad["name"] = "bad"
        bad["inputSchema"]["properties"]["value"]["x-mcp-header"] = "inject\r\nX-Unsafe"
        client, fixture = self.client(self.responder(tools=[annotated_tool(), bad]))
        client.start()
        self.assertEqual([tool["name"] for tool in client.list_tools()], ["echo"])
        self.assertEqual(client.catalog_rejections, 1)
        self.assertIn("excluded", client.logs.snapshot()[-1].text)
        with self.assertRaises(McpError):
            client.call_tool("bad", {"value": "no network"})
        self.assertEqual(len(fixture.requests), 2)

    def test_no_client_capabilities_or_unsupported_interactions_are_advertised(self):
        client, fixture = self.client(self.responder(discovery={**DISCOVERY, "capabilities": {}}))
        client.start()
        self.assertEqual(client.list_tools(), [])
        for method in ("initialize", "subscriptions/listen", "sampling/createMessage", "elicitation/create", "resources/read"):
            with self.assertRaises(McpError):
                client.request(method, {}, timeout_ms=100)
        with self.assertRaises(McpError):
            client.notify("notifications/initialized", {})
        self.assertEqual(len(fixture.requests), 1)
        self.assertEqual(fixture.requests[0].message()["params"]["_meta"], METADATA)

    def test_mrtr_and_unknown_result_types_are_explicit_not_false_success(self):
        for result in (
            {"resultType": "input_required", "requestState": {"malformed": "state"}},
            {"resultType": "complete", "requestState": "not-complete"},
            {"resultType": "input_required", "inputRequests": {"ask": {"method": "elicitation/create", "params": {}}}},
            {"resultType": "unrecognized", "content": []},
        ):
            client, fixture = self.client(self.responder(lambda request: _json_result(request, result)))
            client.start()
            client.list_tools()
            with self.assertRaises(McpError):
                client.call_tool("echo", {"value": "one call"})
            self.assertEqual(len(fixture.requests), 3)

    def test_sse_progress_and_legacy_missing_result_type_are_supported(self):
        def stream(request):
            token = request.message()["params"]["_meta"]["progressToken"]
            return _HttpReply(headers={"Content-Type": "text/event-stream"}, body=(
                b": keepalive\n\n" + _sse_event({"jsonrpc": "2.0", "method": "notifications/progress", "params": {"progressToken": token, "progress": 1}})
                + _sse_event({"jsonrpc": "2.0", "id": request.message()["id"], "result": {"content": [{"type": "text", "text": "ok"}]}})
            ))
        progress = []
        client, _ = self.client(self.responder(stream))
        client.start()
        client.list_tools()
        result = client.call_tool("echo", {"value": "ok"}, progress=progress.append)
        self.assertEqual(result["content"][0]["text"], "ok")
        self.assertEqual(len(progress), 1)

    def test_interrupted_sse_never_resumes_even_with_an_event_id(self):
        client, fixture = self.client(self.responder(lambda request: _HttpReply(
            headers={"Content-Type": "text/event-stream"},
            body=_sse_event({"jsonrpc": "2.0", "method": "notifications/message", "params": {}}, event_id="not-a-resume-permit"),
        )))
        client.start()
        client.list_tools()
        with self.assertRaises(McpError) as error:
            client.call_tool("echo", {"value": "one call"})
        self.assertTrue(error.exception.ambiguous)
        client.close()
        self.assertEqual([request.method for request in fixture.requests], ["POST"] * 3)
        self.assertIsNone(client._last_event_id)

    def test_server_requests_and_unsubscribed_notifications_never_generate_a_post(self):
        for message in (
            {"jsonrpc": "2.0", "id": "server-request", "method": "sampling/createMessage", "params": {}},
            {"jsonrpc": "2.0", "id": "server-request", "method": "elicitation/create", "params": {}},
            {"jsonrpc": "2.0", "method": "notifications/tools/list_changed", "params": {}},
        ):
            def stream(request):
                return _HttpReply(headers={"Content-Type": "text/event-stream"}, body=_sse_event(message) + _sse_event({"jsonrpc": "2.0", "id": request.message()["id"], "result": {"content": []}}))
            client, fixture = self.client(self.responder(stream), enable_elicitation=True)
            client.start()
            client.list_tools()
            with self.assertRaises(McpProtocolError):
                client.call_tool("echo", {"value": "one call"})
            client.close()
            self.assertEqual(len(fixture.requests), 3)

    def test_session_headers_are_rejected_without_adopting_or_deleting_session(self):
        client, fixture = self.client(lambda request: _json_result(request, DISCOVERY, headers={"Mcp-Session-Id": "must-not-adopt"}))
        with self.assertRaises(McpProtocolError) as error:
            client.start()
        self.assertEqual(error.exception.code, "unexpected_session")
        client.close()
        self.assertEqual(len(fixture.requests), 1)
        self.assertIsNone(client._session_id)

    def test_cancellation_closes_socket_without_legacy_notification(self):
        entered = threading.Event()
        release = threading.Event()
        def delayed(request):
            entered.set()
            release.wait(2)
            return _json_result(request, {"content": []})
        client, fixture = self.client(self.responder(delayed))
        client.start()
        client.list_tools()
        cancellation = FakeCancellation()
        errors = []
        def call():
            try:
                client.call_tool("echo", {"value": "cancel"}, cancellation=cancellation)
            except McpError as error:
                errors.append(error)
        worker = threading.Thread(target=call)
        worker.start()
        try:
            self.assertTrue(entered.wait(1))
            cancellation.cancel()
            worker.join(1)
            self.assertFalse(worker.is_alive())
            self.assertIsInstance(errors[0], McpCancelled)
            self.assertEqual(len(fixture.requests), 3)
        finally:
            release.set()
            worker.join(2)

    def test_parallel_calls_and_epoch_pinned_header_schemas_do_not_mix(self):
        barrier = threading.Barrier(2)
        phase = [0]
        old = annotated_tool()["inputSchema"]
        newer = copy.deepcopy(old)
        newer["properties"]["value"]["x-mcp-header"] = "New"
        def respond(request):
            method = request.message()["method"]
            if method == "server/discover":
                return _json_result(request, DISCOVERY)
            if method == "tools/list":
                return _json_result(request, {"tools": [{**annotated_tool(), "inputSchema": old if phase[0] == 0 else newer}]})
            barrier.wait(2)
            params = request.message()["params"]
            state = "state-" + params["arguments"]["value"]
            if "requestState" not in params:
                return _json_result(request, {"resultType": "input_required", "requestState": state})
            self.assertEqual(params["requestState"], state)
            return _json_result(request, {"content": []})
        client, fixture = self.client(respond)
        client.start()
        client.list_tools()
        pinned = normalize_schema(old, require_object=True)
        phase[0] = 1
        client.list_tools()
        errors = []
        def call(value, schema):
            try:
                client.call_tool("echo", {"value": value}, input_schema=schema)
            except BaseException as error:
                errors.append(error)
        workers = [threading.Thread(target=call, args=("old", pinned)), threading.Thread(target=call, args=("new", None))]
        for worker in workers:
            worker.start()
        for worker in workers:
            worker.join(3)
        self.assertEqual(errors, [])
        calls = {request.message()["params"]["arguments"]["value"]: request for request in fixture.requests if request.message()["method"] == "tools/call"}
        self.assertEqual(calls["old"].header("Mcp-Param-Value"), "old")
        self.assertIsNone(calls["old"].header("Mcp-Param-New"))
        self.assertEqual(calls["new"].header("Mcp-Param-New"), "new")
        self.assertIsNone(calls["new"].header("Mcp-Param-Value"))

    def test_resource_methods_have_self_contained_metadata_and_opaque_name_header(self):
        replies = {
            "resources/list": {"resources": [{"uri": "opaque:世界", "name": "test"}]},
            "resources/templates/list": {"resourceTemplates": [{"uriTemplate": "opaque:{name}", "name": "template"}]},
            "resources/read": {"contents": [{"uri": "opaque:世界", "text": "not fetched"}]},
        }
        def respond(request):
            method = request.message()["method"]
            return _json_result(request, {**DISCOVERY, "capabilities": {"resources": {}}} if method == "server/discover" else replies[method])
        client, fixture = self.client(respond)
        client.start()
        self.assertEqual(client.list_tools(), [])
        for method, result in replies.items():
            params = {"uri": "opaque:世界"} if method == "resources/read" else {}
            self.assertEqual(client.request(method, params, timeout_ms=1000), result)
        client.close()
        self.assertEqual(len(fixture.requests), 4)
        for request in fixture.requests:
            message = request.message()
            self.assertEqual(request.method, "POST")
            self.assertEqual(request.header("Mcp-Method"), message["method"])
            self.assertEqual(request.header("MCP-Protocol-Version"), "2026-07-28")
            self.assertEqual(message["params"]["_meta"], METADATA)
            self.assertIsNone(request.header("Mcp-Session-Id"))
            self.assertIsNone(request.header("Last-Event-ID"))
            self.assertEqual(request.header("Mcp-Name"), encode_header_value("opaque:世界") if message["method"] == "resources/read" else None)

    def test_resource_input_required_is_not_an_empty_success_or_a_replay(self):
        def respond(request):
            if request.message()["method"] == "server/discover":
                return _json_result(request, {**DISCOVERY, "capabilities": {"resources": {}}})
            return _json_result(request, {"resultType": "input_required", "requestState": {"opaque": "state"}})
        client, fixture = self.client(respond)
        client.start()
        with self.assertRaises(McpError) as error:
            client.request("resources/read", {"uri": "opaque:ref"}, timeout_ms=1000)
        self.assertEqual(error.exception.code, "invalid_request_state")
        self.assertEqual(len(fixture.requests), 2)

    def test_reserved_metadata_and_continuation_fields_cannot_be_model_authority(self):
        tool = {**annotated_tool(), "inputSchema": {"type": "object"}}
        client, fixture = self.client(self.responder(lambda request: _json_result(request, {"content": []}), tools=[tool]))
        client.start()
        client.list_tools()
        for key in ("inputResponses", "requestState"):
            with self.assertRaises(McpError):
                client.request("tools/call", {"name": "echo", "arguments": {}, key: {}}, timeout_ms=1000)
        self.assertEqual(len(fixture.requests), 2)
        arguments = {"inputResponses": {"not": "a continuation"}, "requestState": "data", "_meta": {"untrusted": True}}
        client.request("tools/call", {
            "name": "echo", "arguments": arguments,
            "_meta": {"io.modelcontextprotocol/protocolVersion": "2025-06-18",
                      "io.modelcontextprotocol/clientCapabilities": {"elicitation": {}},
                      "io.modelcontextprotocol/clientInfo": {"name": "spoofed"}},
        }, timeout_ms=1000)
        params = fixture.requests[-1].message()["params"]
        self.assertEqual(params["arguments"], arguments)
        self.assertEqual(params["_meta"], METADATA)
        self.assertNotIn("requestState", params)
        self.assertNotIn("inputResponses", params)

    def test_ref_sibling_header_survives_epoch_pinning_and_catalog_removal(self):
        tool = annotated_tool()
        tool["inputSchema"]["properties"]["value"].update({"$ref": "#/$defs/bounded"})
        tool["inputSchema"]["$defs"] = {"bounded": {"maxLength": 3}}
        tools = [tool]
        client, fixture = self.client(self.responder(lambda request: _json_result(request, {"content": []}), tools=tools))
        client.start()
        accepted = client.list_tools()
        pinned = normalize_schema(accepted[0]["inputSchema"], require_object=True)
        tools.clear()
        self.assertEqual(client.list_tools(), [])
        with self.assertRaises(McpError):
            client.call_tool("echo", {"value": "old"})
        client.call_tool("echo", {"value": "old"}, input_schema=pinned)
        self.assertEqual(fixture.requests[-1].header("Mcp-Param-Value"), "old")
        self.assertEqual(len(fixture.requests), 4)

    def test_modern_method_not_found_404_is_not_legacy_session_expiration(self):
        client, fixture = self.client(self.responder(lambda request: error_reply(request, -32601, status=404)))
        client.start()
        client.list_tools()
        with self.assertRaises(McpError) as error:
            client.call_tool("echo", {"value": "once"})
        self.assertEqual(error.exception.code, "remote_error")
        self.assertEqual(error.exception.rpc_code, -32601)
        client.close()
        self.assertEqual(len(fixture.requests), 3)

    def test_malformed_terminal_sequences_fail_before_progress_callbacks(self):
        for duplicate in (True, False):
            def stream(request):
                params = request.message()["params"]
                terminal = {"jsonrpc": "2.0", "id": request.message()["id"], "result": {"content": []}}
                notification = {"jsonrpc": "2.0", "method": "notifications/progress", "params": {"progressToken": params["_meta"]["progressToken"], "progress": 1}}
                malformed = terminal if duplicate else {**notification, "result": {}}
                return _HttpReply(headers={"Content-Type": "text/event-stream"}, body=_sse_event(notification) + _sse_event(malformed) + _sse_event(terminal))
            progress = []
            client, fixture = self.client(self.responder(stream))
            client.start()
            client.list_tools()
            with self.assertRaises(McpProtocolError):
                client.call_tool("echo", {"value": "once"}, progress=progress.append)
            self.assertEqual(progress, [])
            self.assertEqual(len(fixture.requests), 3)

    def test_response_size_and_sse_event_budgets_never_retry_actions(self):
        replies = [
            lambda request: _json_result(request, {"content": [{"type": "text", "text": "x" * 5000}]}),
            lambda request: _HttpReply(headers={"Content-Type": "text/event-stream"}, body=(
                _sse_event({"jsonrpc": "2.0", "method": "notifications/message", "params": {}}) * 3
                + _sse_event({"jsonrpc": "2.0", "id": request.message()["id"], "result": {"content": []}}))),
        ]
        for reply in replies:
            client, fixture = self.client(self.responder(reply), bridge_limits=limits(max_frame_bytes=4096))
            client.start()
            client.list_tools()
            with patch("octet_mcp.streamable_http.MAX_HTTP_EVENTS", 2), self.assertRaises(McpError):
                client.call_tool("echo", {"value": "once"})
            self.assertEqual(len(fixture.requests), 3)

    def test_stateless_sse_ids_cannot_rewrite_complete_result_data(self):
        from octet_mcp.config import HttpAuthConfig
        from .test_streamable_http import _TokenProvider

        for token in (None, "fixture-secret-token"):
            def stream(request):
                return _HttpReply(headers={"Content-Type": "text/event-stream"}, body=_sse_event({
                    "jsonrpc": "2.0", "id": request.message()["id"],
                    "result": {"content": [], "structuredContent": {"answer": "answer", "echo": token or "public"}},
                }, event_id="answer"))
            client, fixture = self.client(
                self.responder(stream), credential_provider=_TokenProvider(token),
                config_changes={"auth": HttpAuthConfig(credential="reviewed_remote") if token else None},
            )
            client.start()
            client.list_tools()
            result = client.call_tool("echo", {"value": "once"})
            self.assertEqual(result, {"content": [], "structuredContent": {"answer": "answer", "echo": "[redacted]" if token else "public"}})
            self.assertIsNone(client._last_event_id)
            self.assertEqual(len(fixture.requests), 3)

    def test_mrtr_form_and_resource_url_use_private_bound_handlers(self):
        from .test_interactions import PrivateUI, handler_for, needs_input, URL

        for method in ("tools/call", "resources/read"):
            state = "opaque\x00世界-state"
            ui = PrivateUI('{"name":"private-name"}', 'accept') if method == "tools/call" else PrivateUI('accept')
            cancellation = FakeCancellation()
            progress = []
            def respond(request):
                message = request.message()
                if message["method"] == "server/discover":
                    return _json_result(request, {**DISCOVERY, "capabilities": {"tools": {}, "resources": {}}})
                if message["method"] == "tools/list":
                    return _json_result(request, {"tools": [annotated_tool()]})
                self.assertEqual(message["method"], method)
                params = message["params"]
                if "requestState" not in params:
                    result = needs_input(requestState=state) if method == "tools/call" else needs_input(URL, requestState=state)
                    return _json_result(request, result)
                self.assertEqual(params["requestState"], state)
                expected = {"action": "accept", "content": {"name": "private-name"}} if method == "tools/call" else {"action": "accept"}
                self.assertEqual(params["inputResponses"], {"server-input": expected})
                token = params["_meta"]["progressToken"]
                terminal = {"content": [{"type": "text", "text": "done private-name"}]} if method == "tools/call" else {"contents": [{"uri": "opaque:ref", "text": "done"}]}
                return _HttpReply(headers={"Content-Type": "text/event-stream"}, body=(
                    _sse_event({"jsonrpc": "2.0", "method": "notifications/progress", "params": {"progressToken": token, "progress": 1, "message": "private-name"}})
                    + _sse_event({"jsonrpc": "2.0", "id": message["id"], "result": terminal})
                ))
            client, fixture = self.client(respond, enable_elicitation=True)
            client.start()
            client.list_tools()
            handler = handler_for(ui, token=cancellation)
            if method == "tools/call":
                result = client.call_tool("echo", {"value": "stable"}, cancellation=cancellation, progress=progress.append, interaction_handler=handler)
                self.assertEqual(result["content"][0]["text"], "done [private input]")
                self.assertNotIn("private-name", repr(progress))
            else:
                result = client.request(method, {"uri": "opaque:ref"}, timeout_ms=1000, cancellation=cancellation, progress=progress.append, include_progress_token=True, interaction_handler=handler)
                self.assertEqual(result["contents"][0]["text"], "done")
            calls = fixture.requests[2:]
            self.assertEqual(len(calls), 2)
            self.assertNotEqual(calls[0].message()["id"], calls[1].message()["id"])
            for request in fixture.requests:
                metadata = request.message()["params"]["_meta"]
                expected_caps = handler.client_capabilities if request in calls else {}
                self.assertEqual(metadata["io.modelcontextprotocol/clientCapabilities"], expected_caps)
                self.assertIsNone(request.header("Mcp-Session-Id"))
                self.assertIsNone(request.header("Last-Event-ID"))
                self.assertEqual(request.method, "POST")
            for request in calls:
                self.assertEqual(request.header("Mcp-Method"), method)
                self.assertEqual(request.header("Mcp-Name"), "echo" if method == "tools/call" else "opaque:ref")
                if method == "tools/call":
                    self.assertEqual(request.header("Mcp-Param-Value"), "stable")
            for _, kwargs, _ in ui.inputs:
                self.assertEqual(kwargs, {"parent_request_id": 77, "secret": True})

    def test_state_only_continuations_preserve_opaque_state_without_capability_claims(self):
        state = "opaque\x00世界-state"
        def reply(request):
            params = request.message()["params"]
            if "requestState" not in params:
                return _json_result(request, {"resultType": "input_required", "requestState": state})
            self.assertEqual(params["requestState"], state)
            self.assertNotIn("inputResponses", params)
            return _json_result(request, {"content": [{"type": "text", "text": "complete"}]})
        client, fixture = self.client(self.responder(reply), enable_elicitation=True)
        client.start()
        client.list_tools()
        for _ in range(2):
            self.assertEqual(client.call_tool("echo", {"value": "once"})["content"][0]["text"], "complete")
        self.assertEqual(len(fixture.requests), 6)
        self.assertNotIn("requestState", fixture.requests[4].message()["params"])
        ids = [request.message()["id"] for request in fixture.requests]
        self.assertEqual(len(set(ids)), len(ids))
        for request in fixture.requests:
            self.assertEqual(request.message()["params"]["_meta"]["io.modelcontextprotocol/clientCapabilities"], {})

    def test_elicitation_requires_enablement_actual_handler_and_eligible_method(self):
        from .test_interactions import PrivateUI, handler_for, needs_input

        for enabled in (True, False):
            ui = PrivateUI()
            client, fixture = self.client(self.responder(lambda request: _json_result(request, needs_input())), enable_elicitation=enabled)
            client.start()
            client.list_tools()
            if enabled:
                with self.assertRaises(McpError):
                    client.call_tool("echo", {"value": "once"})
                self.assertEqual(fixture.requests[-1].message()["params"]["_meta"]["io.modelcontextprotocol/clientCapabilities"], {})
            else:
                with self.assertRaises(McpError):
                    client.call_tool("echo", {"value": "once"}, interaction_handler=handler_for(ui))
                self.assertEqual(len(fixture.requests), 2)
            before = len(fixture.requests)
            with self.assertRaises(McpError):
                client.request("tools/list", {}, timeout_ms=1000, interaction_handler=handler_for(ui))
            self.assertEqual(len(fixture.requests), before)
            self.assertEqual(ui.inputs, [])

    def test_mrtr_raw_bytes_events_and_rounds_share_nonresetting_budgets(self):
        for bound in ("bytes", "events", "rounds"):
            def reply(request):
                result = {"resultType": "input_required", "requestState": "opaque"}
                if bound == "bytes":
                    result["_meta"] = {"padding": "x" * 700}
                if bound != "events":
                    return _json_result(request, result)
                return _HttpReply(headers={"Content-Type": "text/event-stream"}, body=(
                    _sse_event({"jsonrpc": "2.0", "method": "notifications/message", "params": {}})
                    + _sse_event({"jsonrpc": "2.0", "id": request.message()["id"], "result": result})))
            client, fixture = self.client(self.responder(reply), bridge_limits=limits(max_frame_bytes=1024 if bound == "bytes" else 4096))
            client.start()
            client.list_tools()
            with patch("octet_mcp.streamable_http.MAX_HTTP_EVENTS", 3), self.assertRaises(McpError) as error:
                client.call_tool("echo", {"value": "once"})
            self.assertEqual(len(fixture.requests), 7 if bound == "rounds" else 4)
            if bound == "rounds":
                self.assertEqual(error.exception.code, "interaction_round_limit")

    def test_mrtr_cancellation_or_owner_loss_after_input_prevents_continuation(self):
        from .test_interactions import PrivateUI, handler_for, needs_input

        for reason in ("cancel", "owner"):
            token = FakeCancellation()
            active = [True]
            class EndingUI(PrivateUI):
                def request_input(self, prompt, **kwargs):
                    if reason == "cancel":
                        token.cancel()
                    else:
                        active[0] = False
                    return super().request_input(prompt, **kwargs)
            ui = EndingUI(None)
            client, fixture = self.client(self.responder(lambda request: _json_result(request, needs_input())), enable_elicitation=True)
            client.start()
            client.list_tools()
            handler = handler_for(ui, token=token, active=lambda owner, parent: active[0])
            with self.assertRaises(McpError):
                client.call_tool("echo", {"value": "once"}, cancellation=token, interaction_handler=handler)
            self.assertEqual(len(fixture.requests), 3)
            self.assertEqual(len(ui.inputs), 1)

    def test_mrtr_deadline_does_not_reset_for_each_continuation(self):
        from octet_mcp.protocol import McpTimeout

        def reply(request):
            return _json_result(request, {"resultType": "input_required", "requestState": "opaque"})
        client, fixture = self.client(self.responder(reply))
        client.start()
        client.list_tools()
        original = McpStreamableHttpClient.request
        deadlines = []

        def request(transport, method, params, **kwargs):
            deadlines.append(kwargs["_deadline"])
            if len(deadlines) == 2:
                # Simulate the transport exhausting its deadline. Assert the
                # actual absolute budget, not that two sockets happen to fit a
                # 150ms wall-clock window on every supported Python/platform.
                raise McpTimeout("request_timeout", "Fixture exhausted the request budget")
            return original(transport, method, params, **kwargs)

        with patch.object(McpStreamableHttpClient, "request", new=request):
            with self.assertRaises(McpTimeout):
                client.call_tool("echo", {"value": "once"})
        self.assertEqual(len(deadlines), 2, "timeout must not replay another round")
        self.assertEqual(deadlines[0], deadlines[1], "continuation must not refund the absolute deadline")
        self.assertEqual(len(fixture.requests), 3)

    def test_dispatch_guard_fences_every_mrtr_round_after_connect(self):
        for method in ("tools/call", "resources/read"):
            connected = []
            guarded = []
            def respond(request):
                message = request.message()
                if message["method"] == "server/discover":
                    return _json_result(request, {**DISCOVERY, "capabilities": {"tools": {}, "resources": {}}})
                if message["method"] == "tools/list":
                    return _json_result(request, {"tools": [annotated_tool()]})
                return _json_result(request, {"resultType": "input_required", "requestState": "opaque"})
            client, fixture = self.client(respond)
            client.start()
            client.list_tools()
            original_connection = client._connection
            def connection(operation, deadline):
                connection = original_connection(operation, deadline)
                original_connect = connection.connect
                def connect():
                    original_connect()
                    connected.append(True)
                connection.connect = connect
                return connection
            def guard():
                # This must run after DNS/TCP/TLS, not just at manager admission.
                self.assertEqual(len(connected), len(guarded) + 1)
                guarded.append(True)
                if len(guarded) == 2:
                    raise McpError("retired_catalog", "Approved catalog was retired during connection setup")
            with patch.object(client, "_connection", side_effect=connection):
                with self.assertRaises(McpError) as error:
                    if method == "tools/call":
                        client.call_tool("echo", {"value": "once"}, dispatch_guard=guard)
                    else:
                        client.request(method, {"uri": "opaque:ref"}, timeout_ms=1000, dispatch_guard=guard)
            self.assertEqual(error.exception.code, "retired_catalog")
            self.assertEqual(len(guarded), 2)
            self.assertEqual(len(connected), 2)
            # The continuation was never sent, despite completing its connection.
            self.assertEqual([request.message()["method"] for request in fixture.requests], ["server/discover", "tools/list", method])


if __name__ == "__main__":
    unittest.main()
