use sexy_tui_rs::rich_text::latex::{render_latex, RenderLatexOptions};

#[test]
fn probe() {
    let cases: &[(&str, bool)] = &[
        // symbols
        (r"\alpha\beta\gamma", false),
        (r"\mathbb{R}^n", false),
        (r"\varnothing \hookrightarrow \twoheadrightarrow", false),
        (r"\lVert x \rVert", false),
        (r"\lfloor x \rfloor \lceil y \rceil", false),
        (r"\hbar \ell \Im \Re", false),
        (r"a \preceq b \sqsubseteq c", false),
        (r"\nexists x", false),
        (r"\checkmark", false),
        (r"\bigcap_{i} A_i", true),
        (r"\coprod_{i} A_i", true),
        // operators
        (r"\det A", false),
        (r"\gcd(a,b)", false),
        (r"\limsup_{n} a_n", true),
        (r"\sup_{x} f", true),
        (r"\operatorname{rank} A", false),
        (r"\operatorname*{arg\,max}_{x} f", true),
        // fractions
        (r"\frac{a}{b}", false),
        (r"\dfrac{a}{b}", true),
        (r"\cfrac{1}{1+x}", true),
        (r"\frac{1}{2}", true),
        (r"\frac{a+b}{c+d}", true),
        (r"\frac{\partial f}{\partial x}", true),
        (r"a/b", false),
        (r"{a \over b}", false),
        (r"\binom{n}{k}", true),
        (r"\sqrt{x}", false),
        (r"\sqrt[3]{x}", false),
        // matrices
        (r"\begin{matrix}a&b\\c&d\end{matrix}", true),
        (r"\begin{pmatrix}a&b\\c&d\end{pmatrix}", true),
        (r"\begin{bmatrix}a&b\\c&d\end{bmatrix}", true),
        (r"\begin{Bmatrix}a&b\\c&d\end{Bmatrix}", true),
        (r"\begin{vmatrix}a&b\\c&d\end{vmatrix}", true),
        (r"\begin{Vmatrix}a&b\\c&d\end{Vmatrix}", true),
        (r"\begin{smallmatrix}a&b\\c&d\end{smallmatrix}", true),
        (r"\begin{array}{cc}a&b\\c&d\end{array}", true),
        (r"\begin{array}{c|c}a&b\\c&d\end{array}", true),
        (r"\left(\begin{matrix}a&b\\c&d\end{matrix}\right)", true),
        (r"\begin{pmatrix}x\end{pmatrix}", true),
        (r"\begin{cases}a&x<0\\b&x>0\end{cases}", false),
        (r"\begin{cases}a&x<0\\b&x=0\\c&x>0\end{cases}", false),
        (r"\begin{aligned}a&=b\\c&=d\end{aligned}", false),
        (r"\begin{align}a&=b\\c&=d\end{align}", false),
        (r"\begin{gather}a=b\\c=d\end{gather}", false),
        (r"\begin{split}a&=b\\&=c\end{split}", false),
        (r"\begin{equation}a=b\end{equation}", false),
        (r"\begin{equation*}a=b\end{equation*}", false),
        (r"\begin{array}{ll}a&b\\c&d\end{array}", true),
        // scripts / accents / wrappers
        (r"x_i^2", false),
        (r"\vec{v}\cdot\vec{w}", false),
        (r"\hat{H}\psi", false),
        (r"\overline{AB}", false),
        (r"\underline{x}", false),
        (r"\overbrace{a+b}^{n}", true),
        (r"\underbrace{a+b}_{n}", true),
        (r"\tilde{n}", false),
        (r"\mathcal{F}", false),
        (r"\mathfrak{g}", false),
        (r"\text{if } x", false),
        (r"\mathrm{d}x", false),
        (r"\left\{x \middle| x>0\right\}", false),
        (r"\left\lVert v \right\rVert", false),
        (r"\bigl(x\bigr)", false),
        (r"\displaystyle\int_0^1", true),
        (r"\lim_{x\to 0}", true),
        (r"\sum_{n=1}^{\infty} \frac{1}{n^2}", true),
        (r"\prod_{i=1}^n i", true),
        (r"\int_{-\infty}^{\infty} e^{-x^2}dx", true),
        (r"\quad a \qquad b", false),
        (r"a \! b", false),
        (r"50\%", false),
        (r"\ \ \%", false),
        // fail-closed expectations
        (r"\begin{tikzpicture}\draw(0,0);\end{tikzpicture}", false),
        (r"\unknown", false),
        (r"\frac{1}", false),
        (r"\substack{i=1\\j=2}", false),
        (r"\hspace{1em}", false),
        (r"\phantom{x}", false),
        (r"\xrightarrow{f}", false),
        (r"\cancel{x}", false),
        (r"\genfrac{}{}{}{}{a}{b}", false),
        (r"\begin{verbatim}x\end{verbatim}", false),
        (r"x^{a^b}", false),
        (r"\text{a \textbf{b}}", false),
    ];
    for (source, display) in cases {
        let out = render_latex(source, RenderLatexOptions { display: *display });
        match out {
            Some(value) => println!("{source:?} D={display} => {value:?}"),
            None => println!("{source:?} D={display} => NONE"),
        }
    }
}
