//! Public image-generation API, the OpenRouter images adapter, and the
//! checked-in image-model catalog.
//!
//! Pi exposes image generation as a provider-neutral `AssistantImages` result
//! over a small `generateImages(model, context, options)` contract. This module
//! carries the same shape in Rust:
//!
//! * [`ImageModelCatalog`] loads the checked-in OpenRouter image-model snapshot
//!   generated by `scripts/refresh-openrouter-image-models.py` (normal builds
//!   and runtime never contact the network);
//! * [`ImageGenerationRequest`] is canonical caller input (text and inline
//!   media), never serialized into chat history;
//! * [`AiClient::generate_images`] runs the OpenRouter images adapter and
//!   returns a bounded [`ImageGenerationResponse`];
//! * [`AiClient::generate_images_reporting`] maps transport failures into the
//!   provider-neutral `error`/`aborted` stop reason exactly like the upstream
//!   adapter instead of returning `Err`.
//!
//! The adapter reads only `data:` URLs and enforces every bound before dispatch
//! or allocation: input count/size, generated-image count/size, and response
//! body size. It performs no retries; retry policy stays host-owned.

use std::collections::BTreeMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use base64::Engine as _;
use serde::{Deserialize, Serialize};

use crate::client::AiClient;
use crate::error::{AiError, ConfigError, DecodeError, HttpError, TransportError, TransportPhase};
use crate::pricing::{cost_of, Cost, TokenRate};
use crate::runtime::HookModelContext;
use crate::types::{Endpoint, EndpointId, EndpointTransport};

/// OpenRouter images api identifier.
pub const OPENROUTER_IMAGES_API: &str = "openrouter-images";
/// OpenRouter credential environment variable.
pub const OPENROUTER_API_KEY_VAR: &str = "OPENROUTER_API_KEY";
/// Maximum number of inputs accepted in one image request.
pub const MAX_IMAGE_INPUTS: usize = 16;
/// Maximum total text bytes accepted in one image request.
pub const MAX_IMAGE_PROMPT_BYTES: usize = 256 * 1024;
/// Maximum inline image bytes accepted in one image request (per image and in
/// total).
pub const MAX_IMAGE_INPUT_BYTES: usize = 32 * 1024 * 1024;
/// Maximum number of generated images accepted in one provider response.
pub const MAX_GENERATED_IMAGES: usize = 8;
/// Maximum decoded bytes accepted for one generated image.
pub const MAX_GENERATED_IMAGE_BYTES: usize = 64 * 1024 * 1024;
/// Maximum provider response body bytes accepted for one image request.
pub const MAX_IMAGE_RESPONSE_BYTES: usize = 256 * 1024 * 1024;
/// Maximum caller header overrides accepted in one image request.
pub const MAX_IMAGE_HEADER_OVERRIDES: usize = 32;
/// Maximum caller header value bytes accepted in one image request.
pub const MAX_IMAGE_HEADER_VALUE_BYTES: usize = 8 * 1024;

/// Wire api used by an image-generation model.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ImageApi {
    /// OpenRouter's chat-completions images surface.
    #[serde(rename = "openrouter-images")]
    OpenRouterImages,
}

impl ImageApi {
    /// Canonical api identifier.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::OpenRouterImages => OPENROUTER_IMAGES_API,
        }
    }
}

/// Input/output modality of an image model.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ImageModality {
    /// Text input/output.
    Text,
    /// Image input/output.
    Image,
}

/// Per-million-token image-model rates in microdollars.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ImagePricing {
    /// Prompt input rate.
    pub input: TokenRate,
    /// Completion output rate.
    pub output: TokenRate,
    /// Cached input read rate.
    pub cache_read: TokenRate,
    /// Cache write rate.
    pub cache_write: TokenRate,
}

impl ImagePricing {
    /// Converts to the canonical pricing table so cost math is shared with chat.
    pub fn to_pricing(&self) -> crate::pricing::Pricing {
        crate::pricing::Pricing {
            input: self.input,
            output: self.output,
            cache_read: self.cache_read,
            cache_write_5m: self.cache_write,
            cache_write_1h: None,
            reasoning: None,
            tiers: Vec::new(),
        }
    }
}

/// One image-generation model record from the checked-in catalog snapshot.
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ImageModelSpec {
    /// Provider-local model id.
    pub id: String,
    /// Human-facing name.
    pub name: String,
    /// Wire api.
    pub api: ImageApi,
    /// Provider id.
    pub provider: String,
    /// Versioned base URL ending with a trailing slash.
    pub base_url: String,
    /// Accepted input modalities.
    pub input: Vec<ImageModality>,
    /// Produced output modalities.
    pub output: Vec<ImageModality>,
    /// Per-million-token rates, or `None` when the provider publishes no
    /// authoritative rate (for example OpenRouter's dynamic-routing
    /// placeholder). Unknown rates never become zero.
    #[serde(default)]
    pub cost: Option<ImagePricing>,
    /// Provider-configuration headers. Values are never shown in `Debug`.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub headers: BTreeMap<String, String>,
}

impl std::fmt::Debug for ImageModelSpec {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ImageModelSpec")
            .field("id", &self.id)
            .field("name", &self.name)
            .field("api", &self.api)
            .field("provider", &self.provider)
            .field("base_url", &self.base_url)
            .field("input", &self.input)
            .field("output", &self.output)
            .field("cost", &self.cost)
            .field("headers", &self.headers.keys().collect::<Vec<_>>())
            .finish()
    }
}

/// Selected image model: catalog facts plus the destination endpoint.
#[derive(Clone)]
pub struct ImageModel {
    /// Catalog record.
    pub spec: Arc<ImageModelSpec>,
    /// Destination endpoint (auth, headers, timeout).
    pub endpoint: Arc<Endpoint>,
}

impl std::fmt::Debug for ImageModel {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ImageModel")
            .field("spec", &self.spec.id)
            .field("endpoint", &self.endpoint.id)
            .finish()
    }
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ImageCatalogFile {
    version: u32,
    models: Vec<ImageModelSpec>,
}

/// Registry of built-in image-generation models.
#[derive(Clone, Default, Debug)]
pub struct ImageModelCatalog {
    models: BTreeMap<(String, String), Arc<ImageModel>>,
}

impl ImageModelCatalog {
    /// Loads the checked-in OpenRouter image-model snapshot.
    pub fn builtin() -> Result<Self, ConfigError> {
        Self::from_json(include_str!("../models/openrouter-image-models.json"))
    }

    /// Parses and validates one catalog snapshot.
    pub fn from_json(raw: &str) -> Result<Self, ConfigError> {
        let file: ImageCatalogFile = serde_json::from_str(raw)
            .map_err(|error| ConfigError::Parse(format!("invalid image-model catalog: {error}")))?;
        if file.version != 1 {
            return Err(ConfigError::Parse(format!(
                "unsupported image-model catalog version {}",
                file.version
            )));
        }
        let mut catalog = Self::default();
        for spec in file.models {
            catalog.register(spec)?;
        }
        if catalog.models.is_empty() {
            return Err(ConfigError::Parse(
                "image-model catalog contained no models".to_owned(),
            ));
        }
        Ok(catalog)
    }

    fn register(&mut self, spec: ImageModelSpec) -> Result<(), ConfigError> {
        if spec.id.trim().is_empty()
            || spec.id.len() > 512
            || spec.provider.trim().is_empty()
            || spec.provider.len() > 128
            || spec.name.trim().is_empty()
            || spec.name.len() > 512
        {
            return Err(ConfigError::Parse(
                "image-model record has an empty or oversized identity".to_owned(),
            ));
        }
        if !spec.output.contains(&ImageModality::Image) {
            return Err(ConfigError::Parse(format!(
                "image model {} does not produce images",
                spec.id
            )));
        }
        if spec.input.is_empty() {
            return Err(ConfigError::Parse(format!(
                "image model {} declares no input modalities",
                spec.id
            )));
        }
        let base_url = url::Url::parse(&spec.base_url).map_err(|error| {
            ConfigError::Parse(format!("invalid image-model base URL: {error}"))
        })?;
        if !base_url.as_str().ends_with('/') {
            return Err(ConfigError::Parse(format!(
                "image-model base URL must end with a trailing slash: {}",
                spec.base_url
            )));
        }
        let endpoint = Arc::new(Endpoint {
            id: EndpointId(format!("{}-images", spec.provider)),
            base_url,
            auth: image_provider_auth(&spec.provider),
            default_headers: http::HeaderMap::new(),
            transport: EndpointTransport::Http,
            runtime: crate::types::RequestRuntime::default(),
            timeout: Duration::from_secs(300),
        });
        crate::catalog::validate_endpoint(&endpoint)?;
        let key = (spec.provider.clone(), spec.id.clone());
        let model = ImageModel {
            spec: Arc::new(spec),
            endpoint,
        };
        if self.models.insert(key, Arc::new(model)).is_some() {
            return Err(ConfigError::Parse(
                "duplicate image-model record".to_owned(),
            ));
        }
        Ok(())
    }

    /// Provider ids with at least one model, sorted.
    pub fn providers(&self) -> Vec<String> {
        let mut providers: Vec<String> = self
            .models
            .keys()
            .map(|(provider, _)| provider.clone())
            .collect();
        providers.dedup();
        providers
    }

    /// Models for one provider, sorted by id.
    pub fn models(&self, provider: &str) -> Vec<ImageModel> {
        self.models
            .iter()
            .filter(|((candidate, _), _)| candidate == provider)
            .map(|(_, model)| (**model).clone())
            .collect()
    }

    /// Resolves one provider/model pair.
    pub fn resolve(&self, provider: &str, id: &str) -> Result<ImageModel, ConfigError> {
        self.models
            .get(&(provider.to_owned(), id.to_owned()))
            .map(|model| (**model).clone())
            .ok_or_else(|| ConfigError::UnknownImageModel {
                provider: provider.to_owned(),
                model: id.to_owned(),
            })
    }

    /// The first built-in model, useful as a deterministic default.
    pub fn default_model(&self) -> Option<ImageModel> {
        self.models.values().next().map(|model| (**model).clone())
    }
}

/// Declared credential route for an image provider.
///
/// Only providers with a documented credential environment variable get one;
/// an unknown provider gets [`crate::auth::Auth::None`] rather than an invented
/// key, so it fails closed instead of dispatching with a guessed credential.
fn image_provider_auth(provider: &str) -> crate::auth::Auth {
    match provider {
        "openrouter" => crate::auth::Auth::BearerEnv {
            var: OPENROUTER_API_KEY_VAR.to_owned(),
        },
        _ => crate::auth::Auth::None,
    }
}

/// One input of an image-generation request.
#[derive(Clone, Debug)]
pub enum ImageInput {
    /// Prompt text.
    Text(String),
    /// Inline image bytes.
    Image {
        /// Media type of the inline image.
        media_type: mime::Mime,
        /// Encoded image bytes.
        data: bytes::Bytes,
    },
}

/// Canonical image-generation request.
#[derive(Clone, Debug, Default)]
pub struct ImageGenerationRequest {
    /// Prompt text and inline images, in order.
    pub inputs: Vec<ImageInput>,
}

impl ImageGenerationRequest {
    /// Creates a request from ordered inputs.
    pub fn new(inputs: Vec<ImageInput>) -> Self {
        Self { inputs }
    }

    /// Creates a request with one text prompt.
    pub fn text(prompt: impl Into<String>) -> Self {
        Self {
            inputs: vec![ImageInput::Text(prompt.into())],
        }
    }

    /// Rejects empty, oversized, or unbounded requests before dispatch.
    pub fn validate(&self) -> Result<(), AiError> {
        if self.inputs.is_empty() {
            return Err(ConfigError::Parse(
                "image generation requires at least one text or image input".to_owned(),
            )
            .into());
        }
        if self.inputs.len() > MAX_IMAGE_INPUTS {
            return Err(ConfigError::Parse(format!(
                "image generation accepts at most {MAX_IMAGE_INPUTS} inputs"
            ))
            .into());
        }
        let mut text_bytes = 0usize;
        let mut image_bytes = 0usize;
        for input in &self.inputs {
            match input {
                ImageInput::Text(text) => {
                    text_bytes = text_bytes.saturating_add(text.len());
                }
                ImageInput::Image { data, .. } => {
                    if data.is_empty() {
                        return Err(ConfigError::Parse(
                            "inline image input must not be empty".to_owned(),
                        )
                        .into());
                    }
                    image_bytes = image_bytes.saturating_add(data.len());
                }
            }
        }
        if text_bytes > MAX_IMAGE_PROMPT_BYTES {
            return Err(ConfigError::Parse(format!(
                "image prompt exceeds the {MAX_IMAGE_PROMPT_BYTES}-byte limit"
            ))
            .into());
        }
        if image_bytes > MAX_IMAGE_INPUT_BYTES {
            return Err(ConfigError::Parse(format!(
                "inline image input exceeds the {MAX_IMAGE_INPUT_BYTES}-byte limit"
            ))
            .into());
        }
        Ok(())
    }
}

/// One decoded generated image.
#[derive(Clone)]
pub struct GeneratedImage {
    /// Media type parsed from the provider's `data:` URL.
    pub media_type: mime::Mime,
    /// Decoded image bytes.
    pub data: bytes::Bytes,
}

impl std::fmt::Debug for GeneratedImage {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("GeneratedImage")
            .field("media_type", &self.media_type)
            .field("bytes", &self.data.len())
            .finish()
    }
}

impl GeneratedImage {
    /// Number of decoded bytes.
    pub fn len(&self) -> usize {
        self.data.len()
    }

    /// Whether the image carries no bytes.
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }
}

/// One output of an image-generation response.
#[derive(Clone, Debug)]
pub enum ImageOutput {
    /// Text companion output (some providers narrate the image).
    Text(String),
    /// Generated image.
    Image(GeneratedImage),
}

/// Provider-neutral image-generation stop reason.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ImageStopReason {
    /// The provider finished.
    Stop,
    /// The provider or transport failed.
    Error,
    /// The caller aborted or cancelled.
    Aborted,
}

/// Provider-neutral image-generation result.
#[derive(Clone, Debug)]
pub struct ImageGenerationResponse {
    /// Wire api.
    pub api: ImageApi,
    /// Provider id.
    pub provider: String,
    /// Provider-local model id.
    pub model: String,
    /// Ordered outputs.
    pub output: Vec<ImageOutput>,
    /// Provider response id.
    pub response_id: Option<String>,
    /// Token usage when the provider reported it.
    pub usage: Option<crate::types::Usage>,
    /// Cost computed from the catalog rates, when usage was reported.
    pub cost: Option<Cost>,
    /// Terminal stop reason.
    pub stop_reason: ImageStopReason,
    /// Failure message for `error`/`aborted` results.
    pub error_message: Option<String>,
    /// Completion time in milliseconds since the Unix epoch.
    pub timestamp_ms: u64,
}

impl ImageGenerationResponse {
    /// Generated images only, in order.
    pub fn images(&self) -> Vec<&GeneratedImage> {
        self.output
            .iter()
            .filter_map(|output| match output {
                ImageOutput::Image(image) => Some(image),
                ImageOutput::Text(_) => None,
            })
            .collect()
    }
}

/// Cooperative cancellation for one image request.
///
/// The adapter checks the flag before dispatch and again after response headers,
/// returning [`AiError::Canceled`]; an in-flight request is cancelled by
/// dropping the returned future (Reqwest then aborts the connection). Cancelling
/// never un-sends provider work or erases usage uncertainty.
#[derive(Clone, Default)]
pub struct ImageCancellation {
    cancelled: Arc<AtomicBool>,
}

impl std::fmt::Debug for ImageCancellation {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ImageCancellation")
            .field("cancelled", &self.is_cancelled())
            .finish()
    }
}

impl ImageCancellation {
    /// Creates an un-cancelled signal.
    pub fn new() -> Self {
        Self::default()
    }

    /// Requests cancellation.
    pub fn cancel(&self) {
        self.cancelled.store(true, Ordering::SeqCst);
    }

    /// Whether cancellation was requested.
    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::SeqCst)
    }
}

/// Host-owned runtime options for one image request.
///
/// It reuses [`crate::runtime::HostRequestOptions`] for the credential override
/// and lifecycle hooks. `fetch` and non-empty `metadata` are refused: there is
/// no host image transport yet and the OpenRouter adapter has no metadata wire
/// field, so silently dropping either would misrepresent the request.
#[derive(Default)]
pub struct ImageGenerationOptions {
    /// Credential override and lifecycle hooks.
    pub runtime: crate::runtime::HostRequestOptions,
    /// Caller header overrides (endpoint < model < caller < authoritative auth).
    pub headers: BTreeMap<String, String>,
    /// Request-local environment overlay for credential and proxy variables.
    pub env: BTreeMap<String, String>,
    /// HTTP timeout in milliseconds; defaults to the endpoint timeout.
    pub timeout_ms: Option<u64>,
    /// Cooperative cancellation signal for this request.
    pub cancel: Option<ImageCancellation>,
    /// Maximum client-side retry attempts. Nonzero is refused: retries are
    /// host-owned.
    pub max_retries: Option<u32>,
    /// Maximum server-requested retry delay. Nonzero is refused.
    pub max_retry_delay_ms: Option<u64>,
}

impl std::fmt::Debug for ImageGenerationOptions {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ImageGenerationOptions")
            .field("runtime", &self.runtime)
            .field("headers", &self.headers.keys().collect::<Vec<_>>())
            .field("env", &self.env.keys().collect::<Vec<_>>())
            .field("timeout_ms", &self.timeout_ms)
            .field(
                "cancel",
                &self.cancel.as_ref().map(|cancel| cancel.is_cancelled()),
            )
            .field("max_retries", &self.max_retries)
            .field("max_retry_delay_ms", &self.max_retry_delay_ms)
            .finish()
    }
}

impl ImageGenerationOptions {
    /// Rejects unbounded, hostile, or host-owned options before dispatch.
    pub fn validate(&self) -> Result<(), AiError> {
        self.runtime.validate()?;
        if self.runtime.fetch.is_some() {
            return Err(ConfigError::Parse(
                "image generation does not support a per-request fetch transport".to_owned(),
            )
            .into());
        }
        if !self.runtime.metadata.is_empty() {
            return Err(ConfigError::Parse(
                "image metadata is not supported by the OpenRouter images adapter".to_owned(),
            )
            .into());
        }
        if self.max_retries.unwrap_or(0) != 0 || self.max_retry_delay_ms.unwrap_or(0) != 0 {
            return Err(ConfigError::Parse(
                "client retries are host-owned; nonzero retry overrides are unsupported".to_owned(),
            )
            .into());
        }
        if self.timeout_ms == Some(0) {
            return Err(
                ConfigError::Parse("timeout_ms must be greater than zero".to_owned()).into(),
            );
        }
        if self.headers.len() > MAX_IMAGE_HEADER_OVERRIDES {
            return Err(ConfigError::Parse(format!(
                "image header overrides exceed the {MAX_IMAGE_HEADER_OVERRIDES}-entry limit"
            ))
            .into());
        }
        for (name, value) in &self.headers {
            let parsed = http::HeaderName::from_bytes(name.as_bytes())
                .map_err(|_| ConfigError::Parse("invalid image header override name".to_owned()))?;
            if crate::runtime::is_reserved_header(&parsed) {
                return Err(ConfigError::ReservedHeader(parsed).into());
            }
            if value.len() > MAX_IMAGE_HEADER_VALUE_BYTES {
                return Err(ConfigError::Parse(format!(
                    "image header override exceeds the {MAX_IMAGE_HEADER_VALUE_BYTES}-byte limit"
                ))
                .into());
            }
            http::HeaderValue::from_str(value).map_err(|_| {
                ConfigError::Parse("invalid image header override value".to_owned())
            })?;
        }
        for (name, value) in &self.env {
            if name.is_empty()
                || name.len() > 256
                || !name
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
            {
                return Err(ConfigError::Parse(
                    "invalid request-local environment variable name".to_owned(),
                )
                .into());
            }
            if value.len() > crate::auth::MAX_ENV_VALUE_BYTES {
                return Err(ConfigError::Parse(
                    "request-local environment value exceeds its byte limit".to_owned(),
                )
                .into());
            }
        }
        Ok(())
    }
}

/// Builds the OpenRouter images request body.
///
/// This is deterministic and network-free so it can be asserted directly by
/// tests and capture fixtures. The caller must validate the request first.
pub fn build_openrouter_images_body(
    model: &ImageModel,
    request: &ImageGenerationRequest,
) -> Result<serde_json::Value, AiError> {
    let mut content = Vec::with_capacity(request.inputs.len());
    for input in &request.inputs {
        match input {
            ImageInput::Text(text) => {
                content.push(serde_json::json!({
                    "type": "text",
                    "text": text,
                }));
            }
            ImageInput::Image { media_type, data } => {
                let encoded = base64::engine::general_purpose::STANDARD.encode(data);
                let url = format!("data:{media_type};base64,{encoded}");
                content.push(serde_json::json!({
                    "type": "image_url",
                    "image_url": {"url": url},
                }));
            }
        }
    }
    let modalities = if model.spec.output.contains(&ImageModality::Text) {
        serde_json::json!(["image", "text"])
    } else {
        serde_json::json!(["image"])
    };
    Ok(serde_json::json!({
        "model": model.spec.id,
        "messages": [{"role": "user", "content": content}],
        "stream": false,
        "modalities": modalities,
    }))
}

fn image_usage(raw: &serde_json::Value) -> Option<crate::types::Usage> {
    let usage = raw.as_object()?;
    let prompt_tokens = usage
        .get("prompt_tokens")
        .and_then(serde_json::Value::as_u64)
        .unwrap_or(0);
    let completion_tokens = usage
        .get("completion_tokens")
        .and_then(serde_json::Value::as_u64)
        .unwrap_or(0);
    let details = usage.get("prompt_tokens_details");
    // `cached_tokens` is the cache-read bucket and `cache_write_tokens` is a
    // separate bucket: neither counter is subtracted from the other, and
    // `prompt_tokens` is their sum plus the uncached input (docs/telemetry.md;
    // the same disjoint-bucket mapping as `openai_chat::map_usage`).
    let cache_read_tokens = details
        .and_then(|details| details.get("cached_tokens"))
        .and_then(serde_json::Value::as_u64)
        .unwrap_or(0);
    let cache_write_tokens = details
        .and_then(|details| details.get("cache_write_tokens"))
        .and_then(serde_json::Value::as_u64)
        .unwrap_or(0);
    let input_tokens = prompt_tokens
        .saturating_sub(cache_read_tokens)
        .saturating_sub(cache_write_tokens);
    Some(crate::types::Usage {
        input_tokens,
        cache_read_tokens,
        cache_write_tokens,
        cache_write_1h_tokens: 0,
        output_tokens: completion_tokens,
        reasoning_tokens: 0,
        total_tokens: input_tokens
            .saturating_add(completion_tokens)
            .saturating_add(cache_read_tokens)
            .saturating_add(cache_write_tokens),
    })
}

fn decode_generated_image(url: &str) -> Result<GeneratedImage, AiError> {
    let Some(rest) = url.strip_prefix("data:") else {
        return Err(ConfigError::Parse("generated image URL is not a data: URL".to_owned()).into());
    };
    let Some((meta, payload)) = rest.split_once(',') else {
        return Err(
            ConfigError::Parse("generated image data URL has no payload".to_owned()).into(),
        );
    };
    let Some(media_type) = meta.strip_suffix(";base64") else {
        return Err(ConfigError::Parse("generated image data URL is not base64".to_owned()).into());
    };
    let media_type: mime::Mime = media_type
        .parse()
        .map_err(|_| ConfigError::Parse("generated image has an invalid media type".to_owned()))?;
    if payload.len() > MAX_GENERATED_IMAGE_BYTES.saturating_mul(4) / 3 + 4 {
        return Err(ConfigError::Parse(format!(
            "generated image exceeds the {MAX_GENERATED_IMAGE_BYTES}-byte limit"
        ))
        .into());
    }
    let data = base64::engine::general_purpose::STANDARD
        .decode(payload)
        .map_err(|error| AiError::Decode(DecodeError::Json(error.to_string())))?;
    if data.len() > MAX_GENERATED_IMAGE_BYTES {
        return Err(ConfigError::Parse(format!(
            "generated image exceeds the {MAX_GENERATED_IMAGE_BYTES}-byte limit"
        ))
        .into());
    }
    Ok(GeneratedImage {
        media_type,
        data: bytes::Bytes::from(data),
    })
}

/// Parses one OpenRouter images response body.
///
/// Non-`data:` URLs and malformed base64 entries are skipped exactly like the
/// upstream adapter; an over-cap image count fails closed instead of silently
/// truncating provider output.
pub fn parse_openrouter_images_response(
    model: &ImageModel,
    value: &serde_json::Value,
) -> Result<ImageGenerationResponse, AiError> {
    let object = value.as_object().ok_or_else(|| {
        AiError::Decode(DecodeError::Json("image response is not an object".into()))
    })?;
    let response_id = object
        .get("id")
        .and_then(serde_json::Value::as_str)
        .map(str::to_owned);
    let usage = object.get("usage").and_then(image_usage);
    let cost = match (&usage, &model.spec.cost) {
        (Some(usage), Some(pricing)) => {
            Some(cost_of(&pricing.to_pricing(), usage).map_err(AiError::Pricing)?)
        }
        _ => None,
    };
    let choice = object
        .get("choices")
        .and_then(serde_json::Value::as_array)
        .and_then(|choices| choices.first())
        .ok_or_else(|| {
            AiError::Decode(DecodeError::Json(
                "image response carried no completion choice".into(),
            ))
        })?;
    let message = choice.get("message").ok_or_else(|| {
        AiError::Decode(DecodeError::Json(
            "image response choice carried no message".into(),
        ))
    })?;
    let mut output = Vec::new();
    if let Some(text) = message.get("content").and_then(serde_json::Value::as_str) {
        if !text.is_empty() {
            output.push(ImageOutput::Text(text.to_owned()));
        }
    }
    let mut image_count = 0usize;
    if let Some(images) = message.get("images").and_then(serde_json::Value::as_array) {
        for image in images {
            let Some(url) = image.get("image_url").and_then(|value| match value {
                serde_json::Value::String(url) => Some(url.as_str()),
                serde_json::Value::Object(object) => {
                    object.get("url").and_then(serde_json::Value::as_str)
                }
                _ => None,
            }) else {
                continue;
            };
            if !url.starts_with("data:") {
                continue;
            }
            image_count += 1;
            if image_count > MAX_GENERATED_IMAGES {
                return Err(ConfigError::Parse(format!(
                    "provider returned more than {MAX_GENERATED_IMAGES} generated images"
                ))
                .into());
            }
            match decode_generated_image(url) {
                Ok(image) => output.push(ImageOutput::Image(image)),
                // A malformed data URL is skipped like an unsupported URL; it
                // never becomes unvalidated bytes.
                Err(_) => continue,
            }
        }
    }
    Ok(ImageGenerationResponse {
        api: model.spec.api,
        provider: model.spec.provider.clone(),
        model: model.spec.id.clone(),
        output,
        response_id,
        usage,
        cost,
        stop_reason: ImageStopReason::Stop,
        error_message: None,
        timestamp_ms: now_ms(),
    })
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis().min(u128::from(u64::MAX)) as u64)
        .unwrap_or(0)
}

fn empty_response(model: &ImageModel, error_message: String) -> ImageGenerationResponse {
    ImageGenerationResponse {
        api: model.spec.api,
        provider: model.spec.provider.clone(),
        model: model.spec.id.clone(),
        output: Vec::new(),
        response_id: None,
        usage: None,
        cost: None,
        stop_reason: ImageStopReason::Error,
        error_message: Some(error_message),
        timestamp_ms: now_ms(),
    }
}

/// Bounded body read for the images adapter.
async fn read_bounded_body(
    res: &mut reqwest::Response,
    max_bytes: usize,
) -> Result<bytes::Bytes, AiError> {
    if let Some(length) = res.content_length() {
        if length > max_bytes as u64 {
            return Err(ConfigError::Parse(format!(
                "image response body exceeds the {max_bytes}-byte limit"
            ))
            .into());
        }
    }
    let mut body = Vec::new();
    while let Some(chunk) = res.chunk().await.map_err(|error| {
        AiError::Transport(TransportError {
            phase: TransportPhase::Body,
            timeout: error.is_timeout(),
            message: format!("image response body failed: {error}"),
        })
    })? {
        if body.len().saturating_add(chunk.len()) > max_bytes {
            return Err(ConfigError::Parse(format!(
                "image response body exceeds the {max_bytes}-byte limit"
            ))
            .into());
        }
        body.extend_from_slice(&chunk);
    }
    Ok(bytes::Bytes::from(body))
}

impl AiClient {
    /// Runs one image-generation request with default options.
    pub async fn generate_images(
        &self,
        model: &ImageModel,
        request: ImageGenerationRequest,
    ) -> Result<ImageGenerationResponse, AiError> {
        self.generate_images_with_options(model, request, ImageGenerationOptions::default())
            .await
    }

    /// Runs one image-generation request and reports failures in-band.
    ///
    /// Mirrors the upstream adapter contract: the returned
    /// [`ImageGenerationResponse`] carries [`ImageStopReason::Error`] and the
    /// redacted message instead of an `Err`. Use
    /// [`Self::generate_images_with_options`] when a typed error is preferred.
    pub async fn generate_images_reporting(
        &self,
        model: &ImageModel,
        request: ImageGenerationRequest,
        options: ImageGenerationOptions,
    ) -> ImageGenerationResponse {
        match self
            .generate_images_with_options(model, request, options)
            .await
        {
            Ok(response) => response,
            Err(error) => {
                let aborted = matches!(error, AiError::Canceled);
                let mut response = empty_response(model, format!("{error}"));
                if aborted {
                    response.stop_reason = ImageStopReason::Aborted;
                }
                response
            }
        }
    }

    /// Runs one image-generation request with host-owned options.
    pub async fn generate_images_with_options(
        &self,
        model: &ImageModel,
        request: ImageGenerationRequest,
        options: ImageGenerationOptions,
    ) -> Result<ImageGenerationResponse, AiError> {
        request.validate()?;
        options.validate()?;
        crate::catalog::validate_endpoint(&model.endpoint)?;
        if !model.spec.output.contains(&ImageModality::Image) {
            return Err(crate::error::UnsupportedError::Image.into());
        }
        let url = model
            .endpoint
            .base_url
            .join("chat/completions")
            .map_err(|error| ConfigError::Parse(format!("invalid image endpoint URL: {error}")))?;
        let client = self.with_environment_overlay(&options.env)?;
        let proxy = client.proxy_for(&url)?;
        if options
            .cancel
            .as_ref()
            .is_some_and(|cancel| cancel.is_cancelled())
        {
            return Err(AiError::Canceled);
        }

        let mut body = serde_json::to_vec(&build_openrouter_images_body(model, &request)?)
            .map_err(|error| AiError::Decode(DecodeError::Json(error.to_string())))?;
        if let Some(hook) = &options.runtime.on_payload {
            let payload: serde_json::Value = serde_json::from_slice(&body)
                .map_err(|error| AiError::Decode(DecodeError::Json(error.to_string())))?;
            let context = HookModelContext {
                id: model.spec.id.clone(),
                provider: model.spec.provider.clone(),
                api: model.spec.api.as_str().to_owned(),
            };
            if let Some(replacement) = hook.on_payload(payload, &context)? {
                body = serde_json::to_vec(&replacement)
                    .map_err(|error| AiError::Decode(DecodeError::Json(error.to_string())))?;
            }
        }

        let mut headers = model.endpoint.default_headers.clone();
        for (name, value) in &model.spec.headers {
            let name = http::HeaderName::from_bytes(name.as_bytes()).map_err(|_| {
                ConfigError::Parse("invalid configured image header name".to_owned())
            })?;
            let mut value = http::HeaderValue::from_str(value).map_err(|_| {
                ConfigError::Parse("invalid configured image header value".to_owned())
            })?;
            value.set_sensitive(true);
            headers.insert(name, value);
        }
        for (name, value) in &options.headers {
            let name = http::HeaderName::from_bytes(name.as_bytes())
                .map_err(|_| ConfigError::Parse("invalid image header override name".to_owned()))?;
            let mut value = http::HeaderValue::from_str(value).map_err(|_| {
                ConfigError::Parse("invalid image header override value".to_owned())
            })?;
            value.set_sensitive(true);
            headers.insert(name, value);
        }
        headers.insert(
            http::header::CONTENT_TYPE,
            http::HeaderValue::from_static("application/json"),
        );
        if let Some(transform) = &options.runtime.transform_headers {
            let before = headers.clone();
            let context = HookModelContext {
                id: model.spec.id.clone(),
                provider: model.spec.provider.clone(),
                api: model.spec.api.as_str().to_owned(),
            };
            transform.transform_headers(&mut headers, &context)?;
            for name in headers.keys() {
                if crate::runtime::is_reserved_header(name) && before.get(name) != headers.get(name)
                {
                    return Err(ConfigError::ReservedHeader(name.clone()).into());
                }
            }
        }
        let resolved = crate::auth::resolve_headers_with_api_key(
            &model.endpoint.auth,
            &options.env,
            options.runtime.api_key.as_ref(),
        )
        .await
        .map_err(AiError::Auth)?;
        let mut redactor = resolved.redactor;
        redactor.include_header_values(&headers);
        if let Some(proxy) = &proxy {
            redactor.include_proxy_url(proxy);
        }
        let mut current_key = None;
        for (key, value) in resolved.headers {
            if let Some(key) = key {
                current_key = Some(key.clone());
                headers.insert(key, value);
            } else if let Some(key) = &current_key {
                headers.append(key.clone(), value);
            }
        }

        let result = async {
            let timeout = options
                .timeout_ms
                .map(Duration::from_millis)
                .unwrap_or(model.endpoint.timeout);
            client.mark_request_dispatch();
            let mut response = match client
                .http_transport()
                .post(url)
                .headers(headers)
                .body(body)
                .timeout(timeout)
                .send()
                .await
            {
                Ok(response) => response,
                Err(error) => {
                    return Err(AiError::Transport(TransportError {
                        phase: if error.is_timeout() {
                            TransportPhase::ResponseHeaders
                        } else {
                            TransportPhase::Connect
                        },
                        timeout: error.is_timeout(),
                        message: format!("image request failed: {error}"),
                    }));
                }
            };
            let status = response.status();
            if options
                .cancel
                .as_ref()
                .is_some_and(|cancel| cancel.is_cancelled())
            {
                return Err(AiError::Canceled);
            }
            if let Some(hook) = &options.runtime.on_response {
                let context = HookModelContext {
                    id: model.spec.id.clone(),
                    provider: model.spec.provider.clone(),
                    api: model.spec.api.as_str().to_owned(),
                };
                hook.on_response(status, response.headers(), &context);
            }
            if !status.is_success() {
                let request_id = response
                    .headers()
                    .get("x-request-id")
                    .and_then(|value| value.to_str().ok())
                    .map(str::to_owned);
                let retry_after = response
                    .headers()
                    .get("retry-after")
                    .and_then(|value| value.to_str().ok())
                    .and_then(|value| value.parse::<u64>().ok())
                    .map(Duration::from_secs);
                let snippet = read_bounded_body(&mut response, 4096)
                    .await
                    .ok()
                    .and_then(|bytes| String::from_utf8(bytes.to_vec()).ok())
                    .map(|body| body.chars().take(2048).collect::<String>());
                return Err(AiError::Http(HttpError {
                    status,
                    request_id,
                    retry_after,
                    provider_code: None,
                    body_snippet: snippet,
                    retryable: status.is_server_error()
                        || status == http::StatusCode::TOO_MANY_REQUESTS,
                }));
            }
            let body = read_bounded_body(&mut response, MAX_IMAGE_RESPONSE_BYTES).await?;
            let value: serde_json::Value = serde_json::from_slice(&body)
                .map_err(|error| AiError::Decode(DecodeError::Json(error.to_string())))?;
            parse_openrouter_images_response(model, &value)
        }
        .await;
        result.map_err(|error| crate::client::sanitize_ai_error(&redactor, error))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_model() -> ImageModel {
        let catalog = ImageModelCatalog::from_json(
            r#"{
                "version": 1,
                "models": [{
                    "id": "test/image-model",
                    "name": "Test Image",
                    "api": "openrouter-images",
                    "provider": "openrouter",
                    "base_url": "https://openrouter.ai/api/v1/",
                    "input": ["text", "image"],
                    "output": ["image", "text"],
                    "cost": {"input": 1000000, "output": 2000000, "cache_read": 100000, "cache_write": 250000}
                }]
            }"#,
        )
        .unwrap();
        catalog.resolve("openrouter", "test/image-model").unwrap()
    }

    fn unpriced_model() -> ImageModel {
        let catalog = ImageModelCatalog::from_json(
            r#"{
                "version": 1,
                "models": [{
                    "id": "test/dynamic-router",
                    "name": "Dynamic Router",
                    "api": "openrouter-images",
                    "provider": "openrouter",
                    "base_url": "https://openrouter.ai/api/v1/",
                    "input": ["text", "image"],
                    "output": ["image", "text"],
                    "cost": null
                }]
            }"#,
        )
        .unwrap();
        catalog
            .resolve("openrouter", "test/dynamic-router")
            .unwrap()
    }

    #[test]
    fn builtin_catalog_loads_the_checked_in_snapshot() {
        let catalog = ImageModelCatalog::builtin().unwrap();
        assert!(!catalog.providers().is_empty());
        assert!(catalog
            .providers()
            .iter()
            .all(|provider| !catalog.models(provider).is_empty()));
        assert!(catalog.default_model().is_some());
    }

    #[test]
    fn body_carries_ordered_inputs_and_modalities() {
        let model = fixture_model();
        let request = ImageGenerationRequest::new(vec![
            ImageInput::Text("draw a cat".to_owned()),
            ImageInput::Image {
                media_type: mime::IMAGE_PNG,
                data: bytes::Bytes::from_static(&[137, 80, 78, 71]),
            },
        ]);
        let body = build_openrouter_images_body(&model, &request).unwrap();
        assert_eq!(body["model"], "test/image-model");
        assert_eq!(body["stream"], false);
        assert_eq!(body["modalities"], serde_json::json!(["image", "text"]));
        assert_eq!(body["messages"][0]["content"][0]["type"], "text");
        assert_eq!(body["messages"][0]["content"][1]["type"], "image_url");
        assert_eq!(
            body["messages"][0]["content"][1]["image_url"]["url"],
            "data:image/png;base64,iVBORw=="
        );
    }

    #[test]
    fn request_bounds_reject_empty_and_oversized_inputs() {
        assert!(ImageGenerationRequest::default().validate().is_err());
        let oversized = ImageGenerationRequest::text("x".repeat(MAX_IMAGE_PROMPT_BYTES + 1));
        assert!(oversized.validate().is_err());
        let empty_image = ImageGenerationRequest::new(vec![ImageInput::Image {
            media_type: mime::IMAGE_PNG,
            data: bytes::Bytes::new(),
        }]);
        assert!(empty_image.validate().is_err());
    }

    #[test]
    fn response_parses_text_multiple_images_and_usage() {
        let model = fixture_model();
        let payload = serde_json::json!({
            "id": "gen-1",
            "choices": [{
                "message": {
                    "content": "here you go",
                    "images": [
                        {"image_url": "data:image/png;base64,iVBORw0KGgo="},
                        {"image_url": {"url": "data:image/jpeg;base64,/9j/4A=="}},
                        {"image_url": "https://example.invalid/not-inline.png"}
                    ]
                }
            }],
            "usage": {
                "prompt_tokens": 100,
                "completion_tokens": 10,
                "prompt_tokens_details": {"cached_tokens": 30, "cache_write_tokens": 10}
            }
        });
        let response = parse_openrouter_images_response(&model, &payload).unwrap();
        assert_eq!(response.response_id.as_deref(), Some("gen-1"));
        assert_eq!(response.stop_reason, ImageStopReason::Stop);
        assert_eq!(response.images().len(), 2);
        assert_eq!(&response.images()[0].media_type, &mime::IMAGE_PNG);
        assert_eq!(&response.images()[1].media_type, &mime::IMAGE_JPEG);
        let usage = response.usage.unwrap();
        // Disjoint buckets: `cached_tokens` is the cache-read bucket, and the
        // uncached input is what remains of `prompt_tokens` after both cache
        // buckets (docs/telemetry.md; `openai_chat::map_usage`).
        assert_eq!(usage.input_tokens, 60);
        assert_eq!(usage.cache_read_tokens, 30);
        assert_eq!(usage.cache_write_tokens, 10);
        assert_eq!(usage.output_tokens, 10);
        assert_eq!(usage.total_tokens, 110);
        assert!(response.cost.is_some());
    }

    #[test]
    fn unpriced_dynamic_router_reports_usage_without_a_cost() {
        let model = unpriced_model();
        let payload = serde_json::json!({
            "id": "gen-2",
            "choices": [{"message": {"images": [
                {"image_url": "data:image/png;base64,iVBORw0KGgo="}
            ]}}],
            "usage": {"prompt_tokens": 5, "completion_tokens": 2}
        });
        let response = parse_openrouter_images_response(&model, &payload).unwrap();
        assert!(response.usage.is_some());
        assert!(response.cost.is_none());
    }

    #[test]
    fn response_skips_malformed_data_urls_and_rejects_over_cap_counts() {
        let model = fixture_model();
        let malformed = serde_json::json!({
            "choices": [{"message": {"images": [
                {"image_url": "data:image/png;base64,%%%"},
                {"image_url": 42}
            ]}}]
        });
        let response = parse_openrouter_images_response(&model, &malformed).unwrap();
        assert!(response.output.is_empty());

        let images: Vec<serde_json::Value> = (0..=MAX_GENERATED_IMAGES)
            .map(|_| serde_json::json!({"image_url": "data:image/png;base64,iVBORw0KGgo="}))
            .collect();
        let over_cap = serde_json::json!({"choices": [{"message": {"images": images}}]});
        assert!(parse_openrouter_images_response(&model, &over_cap).is_err());
    }

    #[test]
    fn options_refuse_host_owned_fields() {
        let options = ImageGenerationOptions {
            max_retries: Some(1),
            ..Default::default()
        };
        assert!(options.validate().is_err());
        let options = ImageGenerationOptions {
            timeout_ms: Some(0),
            ..Default::default()
        };
        assert!(options.validate().is_err());
        let mut options = ImageGenerationOptions::default();
        options
            .headers
            .insert("authorization".to_owned(), "forged".to_owned());
        assert!(options.validate().is_err());
        let mut options = ImageGenerationOptions::default();
        options.env.insert("bad-name!".to_owned(), "x".to_owned());
        assert!(options.validate().is_err());
    }

    #[test]
    fn catalog_rejects_unknown_and_malformed_records() {
        let error = ImageModelCatalog::from_json("{\"version\":1,\"models\":[]}").unwrap_err();
        assert!(matches!(error, ConfigError::Parse(_)));
        let unknown = ImageModelCatalog::from_json(
            r#"{"version":1,"models":[{"id":"x","name":"X","api":"openrouter-images","provider":"openrouter","base_url":"https://openrouter.ai/api/v1/","input":["text"],"output":["text"]}]}"#,
        )
        .unwrap_err();
        assert!(matches!(unknown, ConfigError::Parse(_)));
        let catalog = ImageModelCatalog::builtin().unwrap();
        assert!(matches!(
            catalog.resolve("openrouter", "missing/model"),
            Err(ConfigError::UnknownImageModel { .. })
        ));
    }
}
