// Generated by oracle.mjs from hash-verified Pi 1.0.2 system-theme.ts.
// Copyright (c) 2025 Mario Zechner. MIT license: see LICENSE.
// The solver is independently ported in ../pi.rs; these are upstream recipe data.
use super::{Curve, Family, Rule, Token};

pub(super) const FAMILIES: &[Family] = &[
    Family {
        hue: 231.49,
        min: 0.02,
        max: 0.08,
    }, // neutral
    Family {
        hue: 231.49,
        min: 0.1,
        max: 0.68,
    }, // blue
    Family {
        hue: 158.68,
        min: 0.1,
        max: 0.76,
    }, // green
    Family {
        hue: 20.0,
        min: 0.1,
        max: 0.92,
    }, // red
    Family {
        hue: 82.36,
        min: 0.5,
        max: 1.0,
    }, // yellow
    Family {
        hue: 52.0,
        min: 0.12,
        max: 0.85,
    }, // orange
    Family {
        hue: 295.0,
        min: 0.2,
        max: 0.6,
    }, // violet
    Family {
        hue: 202.43,
        min: 0.1,
        max: 0.74,
    }, // calamine
    Family {
        hue: 231.49,
        min: 0.08,
        max: 0.2,
    }, // thinkingSlate
    Family {
        hue: 231.49,
        min: 0.2,
        max: 0.45,
    }, // thinkingBlue
    Family {
        hue: 263.25,
        min: 0.3,
        max: 0.6,
    }, // thinkingPeriwinkle
    Family {
        hue: 295.0,
        min: 0.4,
        max: 0.75,
    }, // thinkingViolet
    Family {
        hue: 337.5,
        min: 0.5,
        max: 0.85,
    }, // thinkingMagenta
    Family {
        hue: 20.0,
        min: 0.95,
        max: 1.0,
    }, // thinkingRed
];

pub(super) const TOKENS: &[Token] = &[
    Token {
        name: "selectedBg",
        family: 1,
        slot: 4,
        panel: true,
        foreground: false,
    },
    Token {
        name: "searchMatchBg",
        family: 5,
        slot: 3,
        panel: true,
        foreground: false,
    },
    Token {
        name: "userMessageBg",
        family: 1,
        slot: 4,
        panel: true,
        foreground: false,
    },
    Token {
        name: "customMessageBg",
        family: 6,
        slot: 5,
        panel: true,
        foreground: false,
    },
    Token {
        name: "toolPendingBg",
        family: 0,
        slot: 8,
        panel: true,
        foreground: false,
    },
    Token {
        name: "toolSuccessBg",
        family: 2,
        slot: 2,
        panel: true,
        foreground: false,
    },
    Token {
        name: "toolErrorBg",
        family: 3,
        slot: 1,
        panel: true,
        foreground: false,
    },
    Token {
        name: "text",
        family: 0,
        slot: 8,
        panel: false,
        foreground: true,
    },
    Token {
        name: "userMessageText",
        family: 0,
        slot: 8,
        panel: false,
        foreground: true,
    },
    Token {
        name: "customMessageText",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "toolTitle",
        family: 0,
        slot: 8,
        panel: false,
        foreground: true,
    },
    Token {
        name: "syntaxOperator",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxPunctuation",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "muted",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "dim",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingText",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "toolOutput",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdLinkUrl",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdQuote",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdQuoteBorder",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdHr",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdCodeBlockBorder",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "toolDiffContext",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxComment",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "scrollbarTrack",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "scrollbarThumb",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "searchMatchText",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "borderMuted",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "accent",
        family: 6,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "borderAccent",
        family: 6,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "customMessageLabel",
        family: 6,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdCode",
        family: 6,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdListBullet",
        family: 6,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxType",
        family: 6,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "border",
        family: 1,
        slot: 4,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdLink",
        family: 1,
        slot: 4,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxKeyword",
        family: 1,
        slot: 4,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxVariable",
        family: 7,
        slot: 6,
        panel: false,
        foreground: false,
    },
    Token {
        name: "success",
        family: 2,
        slot: 2,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdCodeBlock",
        family: 2,
        slot: 2,
        panel: false,
        foreground: false,
    },
    Token {
        name: "toolDiffAdded",
        family: 2,
        slot: 2,
        panel: false,
        foreground: false,
    },
    Token {
        name: "bashMode",
        family: 2,
        slot: 2,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxNumber",
        family: 2,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "error",
        family: 3,
        slot: 1,
        panel: false,
        foreground: false,
    },
    Token {
        name: "toolDiffRemoved",
        family: 3,
        slot: 1,
        panel: false,
        foreground: false,
    },
    Token {
        name: "warning",
        family: 4,
        slot: 3,
        panel: false,
        foreground: false,
    },
    Token {
        name: "mdHeading",
        family: 4,
        slot: 3,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxFunction",
        family: 4,
        slot: 3,
        panel: false,
        foreground: false,
    },
    Token {
        name: "syntaxString",
        family: 5,
        slot: 2,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingOff",
        family: 0,
        slot: 8,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingMinimal",
        family: 8,
        slot: 4,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingLow",
        family: 9,
        slot: 4,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingMedium",
        family: 10,
        slot: 6,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingHigh",
        family: 11,
        slot: 5,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingXhigh",
        family: 12,
        slot: 13,
        panel: false,
        foreground: false,
    },
    Token {
        name: "thinkingMax",
        family: 13,
        slot: 1,
        panel: false,
        foreground: false,
    },
];

pub(super) const LEVELS: &[[Curve; 2]] = &[
    [
        Curve {
            coefficients: [0.29131, -0.39746, 2.33185, -0.85524, -1.2076, 0.86276],
            reachable: [0.0, 0.979],
        },
        Curve {
            coefficients: [-3.74073, 27.94549, -78.44258, 112.6798, -79.60015, 22.11277],
            reachable: [0.348, 1.0],
        },
    ], // panel
    [
        Curve {
            coefficients: [0.39028, -0.23015, 0.83573, 2.43829, -4.38292, 2.01582],
            reachable: [0.0, 0.946],
        },
        Curve {
            coefficients: [
                -5.24921, 38.37322, -107.28833, 152.10005, -106.17127, 29.18061,
            ],
            reachable: [0.368, 1.0],
        },
    ], // track
    [
        Curve {
            coefficients: [0.52988, -0.05809, -0.30924, 4.63567, -6.52933, 2.89108],
            reachable: [0.0, 0.873],
        },
        Curve {
            coefficients: [
                -28.27749, 182.85284, -469.62416, 603.15916, -384.59976, 97.35147,
            ],
            reachable: [0.51, 1.0],
        },
    ], // thinking0
    [
        Curve {
            coefficients: [0.55278, -0.03667, -0.45659, 4.95347, -6.90265, 3.0706],
            reachable: [0.0, 0.858],
        },
        Curve {
            coefficients: [
                -37.10484, 235.86282, -596.62344, 754.3633, -474.00763, 118.3551,
            ],
            reachable: [0.535, 1.0],
        },
    ], // thinking1
    [
        Curve {
            coefficients: [0.57486, -0.01765, -0.58987, 5.25227, -7.27175, 3.25532],
            reachable: [0.0, 0.842],
        },
        Curve {
            coefficients: [
                -59.89653, 377.05024, -945.07843, 1182.03145, -734.96375, 181.68658,
            ],
            reachable: [0.556, 1.0],
        },
    ], // thinking2
    [
        Curve {
            coefficients: [0.59621, -0.00062, -0.71148, 5.53588, -7.6392, 3.44606],
            reachable: [0.0, 0.827],
        },
        Curve {
            coefficients: [
                -72.07122,
                445.84082,
                -1099.57352,
                1353.88793,
                -829.53392,
                202.26164,
            ],
            reachable: [0.58, 1.0],
        },
    ], // thinking3
    [
        Curve {
            coefficients: [0.61691, 0.01462, -0.82288, 5.80651, -8.00641, 3.64333],
            reachable: [0.0, 0.811],
        },
        Curve {
            coefficients: [
                -110.14338,
                674.21488,
                -1645.75941,
                2004.32367,
                -1215.15899,
                293.3183,
            ],
            reachable: [0.6, 1.0],
        },
    ], // thinking4
    [
        Curve {
            coefficients: [0.63702, 0.02826, -0.92498, 6.06465, -8.37246, 3.84651],
            reachable: [0.0, 0.795],
        },
        Curve {
            coefficients: [
                -175.47701,
                1063.54495,
                -2570.70594,
                3098.80776,
                -1860.15527,
                444.76392,
            ],
            reachable: [0.62, 1.0],
        },
    ], // thinking5
    [
        Curve {
            coefficients: [0.65658, 0.04044, -1.01835, 6.30989, -8.73529, 4.05439],
            reachable: [0.0, 0.779],
        },
        Curve {
            coefficients: [
                -183.81712,
                1094.70055,
                -2602.68539,
                3088.71276,
                -1826.91131,
                430.75931,
            ],
            reachable: [0.643, 1.0],
        },
    ], // thinking6
    [
        Curve {
            coefficients: [0.56762, -0.02475, -0.5383, 5.12628, -7.10931, 3.17324],
            reachable: [0.0, 0.848],
        },
        Curve {
            coefficients: [
                -232.85459,
                1376.54473,
                -3249.11801,
                3827.91186,
                -2248.29472,
                526.55751,
            ],
            reachable: [0.657, 1.0],
        },
    ], // subtle
    [
        Curve {
            coefficients: [0.60323, 0.00278, -0.73328, 5.57157, -7.68067, 3.46933],
            reachable: [0.0, 0.823],
        },
        Curve {
            coefficients: [
                -82.89897,
                511.01355,
                -1255.98095,
                1540.76821,
                -940.68087,
                228.58523,
            ],
            reachable: [0.586, 1.0],
        },
    ], // thumb
    [
        Curve {
            coefficients: [0.66937, 0.04704, -1.06871, 6.43941, -8.9332, 4.17229],
            reachable: [0.0, 0.77],
        },
        Curve {
            coefficients: [
                -1554.52576,
                8733.56817,
                -19604.93507,
                21977.72696,
                -12300.99599,
                2749.81288,
            ],
            reachable: [0.751, 1.0],
        },
    ], // readable
    [
        Curve {
            coefficients: [0.7303, 0.07695, -1.31626, 7.1681, -10.14436, 4.92846],
            reachable: [0.0, 0.712],
        },
        Curve {
            coefficients: [
                -4948.31942,
                26870.91986,
                -58334.48399,
                63280.17197,
                -34298.01053,
                7430.30146,
            ],
            reachable: [0.811, 1.0],
        },
    ], // emphasis
    [
        Curve {
            coefficients: [0.86713, 0.05232, -0.89428, 4.79014, -5.5432, 1.75023],
            reachable: [0.0, 0.542],
        },
        Curve {
            coefficients: [
                -8570.89457,
                43954.60805,
                -90084.00702,
                92220.6791,
                -47152.15802,
                9632.27113,
            ],
            reachable: [0.867, 1.0],
        },
    ], // textOnPanel
    [
        Curve {
            coefficients: [0.89242, 0.02311, -0.44862, 2.34417, -0.06084, -2.63844],
            reachable: [0.0, 0.5],
        },
        Curve {
            coefficients: [
                -2004.67048,
                6664.47299,
                -6060.70202,
                -1792.61209,
                5133.82359,
                -1939.85583,
            ],
            reachable: [0.894, 1.0],
        },
    ], // text
];

pub(super) const RULES: &[Rule] = &[
    Rule {
        token: 2,
        on: &[56],
        level: 0,
    },
    Rule {
        token: 4,
        on: &[56],
        level: 0,
    },
    Rule {
        token: 5,
        on: &[56],
        level: 0,
    },
    Rule {
        token: 6,
        on: &[56],
        level: 0,
    },
    Rule {
        token: 0,
        on: &[56],
        level: 0,
    },
    Rule {
        token: 1,
        on: &[56],
        level: 0,
    },
    Rule {
        token: 3,
        on: &[56],
        level: 0,
    },
    Rule {
        token: 7,
        on: &[56],
        level: 14,
    },
    Rule {
        token: 7,
        on: &[0],
        level: 13,
    },
    Rule {
        token: 8,
        on: &[2],
        level: 13,
    },
    Rule {
        token: 10,
        on: &[4, 5, 6],
        level: 13,
    },
    Rule {
        token: 28,
        on: &[56, 0, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 38,
        on: &[56, 0, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 43,
        on: &[56, 0, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 45,
        on: &[56, 0, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 13,
        on: &[56, 0, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 14,
        on: &[56, 0, 3, 4, 5, 6],
        level: 9,
    },
    Rule {
        token: 15,
        on: &[56],
        level: 11,
    },
    Rule {
        token: 9,
        on: &[3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 30,
        on: &[56, 3, 0, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 16,
        on: &[56, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 46,
        on: &[56, 2, 3],
        level: 11,
    },
    Rule {
        token: 35,
        on: &[56, 2, 3],
        level: 11,
    },
    Rule {
        token: 17,
        on: &[56, 2, 3],
        level: 11,
    },
    Rule {
        token: 31,
        on: &[56, 2, 3],
        level: 11,
    },
    Rule {
        token: 18,
        on: &[56, 2, 3],
        level: 11,
    },
    Rule {
        token: 21,
        on: &[56, 2, 3],
        level: 11,
    },
    Rule {
        token: 32,
        on: &[56, 2, 3],
        level: 11,
    },
    Rule {
        token: 39,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 40,
        on: &[56, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 44,
        on: &[56, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 22,
        on: &[56, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 23,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 36,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 47,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 37,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 48,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 42,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 33,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 11,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 12,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 26,
        on: &[1],
        level: 11,
    },
    Rule {
        token: 41,
        on: &[56],
        level: 11,
    },
    Rule {
        token: 34,
        on: &[56],
        level: 11,
    },
    Rule {
        token: 29,
        on: &[56],
        level: 11,
    },
    Rule {
        token: 27,
        on: &[56],
        level: 9,
    },
    Rule {
        token: 19,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 20,
        on: &[56, 2, 3, 4, 5, 6],
        level: 11,
    },
    Rule {
        token: 24,
        on: &[56],
        level: 1,
    },
    Rule {
        token: 25,
        on: &[24],
        level: 10,
    },
    Rule {
        token: 49,
        on: &[56],
        level: 2,
    },
    Rule {
        token: 50,
        on: &[56],
        level: 3,
    },
    Rule {
        token: 51,
        on: &[56],
        level: 4,
    },
    Rule {
        token: 52,
        on: &[56],
        level: 5,
    },
    Rule {
        token: 53,
        on: &[56],
        level: 6,
    },
    Rule {
        token: 54,
        on: &[56],
        level: 7,
    },
    Rule {
        token: 55,
        on: &[56],
        level: 8,
    },
];

pub(super) const SOLVE_ORDER: &[usize] = &[
    2, 4, 5, 6, 0, 1, 3, 7, 8, 10, 28, 38, 43, 45, 13, 14, 15, 9, 30, 16, 46, 35, 17, 31, 18, 21,
    32, 39, 40, 44, 22, 23, 36, 47, 37, 48, 42, 33, 11, 12, 26, 41, 34, 29, 27, 19, 20, 24, 25, 49,
    50, 51, 52, 53, 54, 55,
];
pub(super) const READABLE_FLOOR: [usize; 2] = [11, 9];
pub(super) const FOREGROUND_LEVEL: usize = 12;
